// src/components/layout/NavPanel.svelte
<script lang="ts">
	import { t } from '@lib/i18n';

	type ButtonData = {
		name: string;
		view: string;
	};

	export let buttons: ButtonData[] = [];
	export let activeView: string = 'profile';

	import { createEventDispatcher } from 'svelte';
	const dispatch = createEventDispatcher();

	let isMenuOpen = false;

	const setActive = (view: string) => {
		dispatch('navigate', { view });
		isMenuOpen = false;
	};
</script>

<div class="relative">
	<!-- Desktop Navigation -->
	<div class="hidden md:flex">
		{#each buttons as { name, view }}
			<button
				class="flex-1 px-4 py-2 text-center text-sm font-medium
					border border-gray-400 dark:border-gray-200 hover:bg-gray-500 dark:hover:bg-gray-100 bg-neutral-100 dark:bg-dark dark:text-light focus:outline-none
					{activeView === view ? 'border-b-transparent bg-white font-semibold' : 'text-gray-600 font-thin'}"
				onclick={() => setActive(view)}
			>
				{$t(name)}
			</button>
		{/each}
	</div>

	<!-- Hamburger Menu for Smaller Screens -->
	<div class="flex md:hidden justify-center">
		<div class="flex flex-col items-center w-full relative">
			<!-- Hamburger Icon -->
			<button
				class="p-2 rounded-md focus:outline-none text-gray-100"
				onclick={() => (isMenuOpen = !isMenuOpen)}
				aria-label="Open menu"
			>
				<svg
					class="w-6 h-6"
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke="currentColor"
					stroke-width="2"
				>
					<path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
				</svg>
			</button>

			<!-- Extended Menu -->
			{#if isMenuOpen}
				<div class="absolute top-full left-0 z-50 w-full bg-white text-gray-100">
					{#each buttons as { name, view }}
						<button class="w-full px-4 py-2 text-left text-sm" onclick={() => setActive(view)}>
							{$t(name)}
						</button>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

// apps/frontend/src/components/layout/NavPanel.tsx
import { Icon } from "@graminate/ui";
import { useState } from "react";
import type { NavPanel } from "@/types/card-props";

const NavPanel = ({ buttons, activeView, onNavigate }: NavPanel) => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <div className="relative">
      {/* Desktop Navigation */}
      <div className="hidden md:flex">
        {buttons.map(({ name, view }) => (
          <button
            key={view}
            className={`flex-1 px-4 py-2 text-center text-sm font-medium
               dark:border-gray-200 hover:bg-gray-500 dark:hover:bg-gray-700 bg-neutral-100 dark:bg-gray-600 dark:text-light focus:outline-none shadow-md
              ${
                activeView === view
                  ? "border-b-transparent bg-white font-semibold"
                  : "text-dark font-thin"
              }`}
            onClick={() => onNavigate(view)}
          >
            {name}
          </button>
        ))}
      </div>

      {/* Mobile Navigation (Hamburger Menu) */}
      <div className="flex md:hidden justify-center">
        <div className="flex flex-col items-center w-full relative">
          {/* Hamburger Icon */}
          <button
            className="p-2 rounded-md focus:outline-none text-gray-100"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            aria-label="Open menu"
          >
            <Icon type={"menu" as any} className="size-6" />
          </button>

          {/* Dropdown Menu */}
          {isMenuOpen && (
            <div className="absolute top-full left-0 z-50 w-full bg-white text-gray-100 shadow-md">
              {buttons.map(({ name, view }) => (
                <button
                  key={view}
                  className="w-full px-4 py-2 text-left text-sm hover:bg-gray-200"
                  onClick={() => {
                    onNavigate(view);
                    setIsMenuOpen(false);
                  }}
                >
                  {name}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default NavPanel;
