// src/components/modals/TaskModal.svelte
<script lang="ts">
	import Button from '@ui/Button.svelte';
	import CustomTextArea from '@ui/CustomTextArea.svelte';
	import { onMount } from 'svelte';

	export let isOpen: boolean;
	export let taskDetails: { id: string; title: string };
	export let projectName: string | null;
	export let onClose: () => void;

	let isEditing = false;
	let editedTitle = taskDetails.title;
	let description: string = '';
	let existingDescriptionId: string | null = null;

	let isFlagged = false;
	let showDropdown = false;

	function closeModal() {
		if (onClose) onClose();
	}

	function startEditing() {
		isEditing = true;
	}

	function saveTitle() {
		isEditing = false;
		taskDetails.title = editedTitle;
		localStorage.setItem(`task-${taskDetails.id}`, editedTitle);
	}

	function toggleDropdown() {
		showDropdown = !showDropdown;
	}

	function toggleFlag() {
		isFlagged = !isFlagged;
		showDropdown = false;
	}

	onMount(() => {
		const savedTitle = localStorage.getItem(`task-${taskDetails.id}`);
		if (savedTitle) {
			taskDetails.title = savedTitle;
			editedTitle = savedTitle;
		}
	});
</script>

{#if isOpen}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg p-6 h-[80%] w-[1200px] shadow-lg relative">
			<!-- Ellipse Button and Cross Button -->
			<div class="absolute top-3 right-3 flex items-center space-x-2">
				<!-- Options Button -->
				<div class="relative">
					<button
						class="p-2 rounded-md hover:bg-gray-400 focus:outline-none"
						aria-label="Options"
						on:click={toggleDropdown}
					>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							stroke-width="1.5"
							stroke="currentColor"
							class="size-5"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
							/>
						</svg>
					</button>
					<!-- Dropdown -->
					{#if showDropdown}
						<div class="absolute right-0 mt-2 w-40 bg-white shadow-md rounded">
							<button
								class="block w-full text-left px-4 py-2 text-sm hover:bg-gray-400"
								on:click={toggleFlag}
							>
								{isFlagged ? 'Remove Flag' : 'Add Flag'}
							</button>
						</div>
					{/if}
				</div>

				<!-- Close Button -->
				<button
					class="p-2 rounded-md hover:bg-gray-400 focus:outline-none"
					aria-label="Close"
					on:click={closeModal}
				>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						fill="none"
						viewBox="0 0 24 24"
						stroke-width="1.5"
						stroke="currentColor"
						class="size-5"
					>
						<path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
					</svg>
				</button>
			</div>

			<p class="text-gray-300 text-sm">{projectName} / {taskDetails.id}</p>

			<div class="grid grid-cols-[60%_40%] gap-4 mt-4">
				<!-- Left Column -->
				<div>
					{#if isEditing}
						<input
							type="text"
							bind:value={editedTitle}
							class="text-gray-200 text-lg font-bold rounded-md w-full p-2"
							on:blur={saveTitle}
							on:keydown={(e) => e.key === 'Enter' && saveTitle()}
						/>
					{:else}
						<button
							class="w-full text-gray-200 text-lg hover:bg-gray-50 hover:cursor-pointer bg-transparent rounded-md p-0"
							on:click={startEditing}
						>
							<span class="flex p-2 font-bold">
								{taskDetails.title}
							</span>
						</button>
					{/if}
					<div class="mt-4">
						<p class="text-gray-200 font-bold text-md mb-2">Description</p>
						<CustomTextArea
							placeholder="Add your description here..."
							value={description}
							onInput={(val) => (description = val)}
							descriptionId={existingDescriptionId}
						/>
					</div>
				</div>

				<!-- Right Column -->
				<div>
					<div class="flex flex-row gap-4 justify-start items-center">
						<Button text="Update" style="primary" />
						{#if isFlagged}
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								stroke-width="1.5"
								stroke="currentColor"
								class="size-6"
							>
								<path
									stroke-linecap="round"
									stroke-linejoin="round"
									d="M3 3v1.5M3 21v-6m0 0 2.77-.693a9 9 0 0 1 6.208.682l.108.054a9 9 0 0 0 6.086.71l3.114-.732a48.524 48.524 0 0 1-.005-10.499l-3.11.732a9 9 0 0 1-6.085-.711l-.108-.054a9 9 0 0 0-6.208-.682L3 4.5M3 15V4.5"
								/>
							</svg>
						{/if}
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}

// apps/frontend/src/components/modals/crm/TaskModal.tsx
import { Dropdown, Icon } from "@graminate/ui";
import React, { useState, useEffect, KeyboardEvent } from "react";
import CustomTextArea from "@/components/ui/CustomTextArea";

import Swal from "sweetalert2";
import TextField from "@/components/ui/TextField";
import Button from "@/components/ui/Button";

type TaskModalProps = {
  isOpen: boolean;
  taskDetails: {
    id: string;
    columnId: string;
    title: string;
    status: string;
    priority?: string;
    description?: string;
    deadline?: string;
  };
  projectName: string;
  columns?: { id: string; title: string }[];
  availableLabels: string[];
  onClose: () => void;
  updateTask: (updatedTask: {
    id: string;
    title: string;
    columnId: string;
    status: string;
    priority?: string;
    description?: string;
    deadline?: string;
  }) => Promise<void>;
  deleteTask: (taskId: string) => Promise<void>;
};

const TaskModal = ({
  isOpen,
  taskDetails,
  projectName,
  columns = [],
  availableLabels,
  onClose,
  deleteTask,
  updateTask,
}: TaskModalProps) => {
  const [isEditingTitle, setIsEditingTitle] = useState(false);
  const [editedTitle, setEditedTitle] = useState(taskDetails.title);
  const [isEditingDescription, setIsEditingDescription] = useState(false);
  const [editedDescription, setEditedDescription] = useState(
    taskDetails.description ?? ""
  );
  const [showDropdown, setShowDropdown] = useState(false);
  const priorityOptions = ["Low", "Medium", "High"];
  
  // Use dynamic columns if provided
  const statusOptions = columns.length > 0
    ? columns.map(c => c.title)
    : ["To Do", "In Progress", "Checks", "Completed"];

  const [taskData, setTaskData] = useState({
    ...taskDetails,
    priority: taskDetails.priority || "Medium",
    description: taskDetails.description ?? "",
    deadline: taskDetails.deadline ?? "",
  });

  const updateTaskField = async (
    field: keyof typeof taskData,
    value: string
  ) => {
    const originalValue = taskData[field];
    const updatedTaskData = { ...taskData, [field]: value };
    setTaskData(updatedTaskData);

    try {
      await updateTask(updatedTaskData);
    } catch (error) {
      console.error(`Failed to update ${field}:`, error);
      setTaskData((prev) => ({
        ...prev,
        [field]: originalValue,
      }));
      Swal.fire({
        title: "Update Failed",
        text: `Could not update ${field}`,
        icon: "error",
      });
    }
  };

  const handleDeadlineChange = async (newDeadline: string) => {
    const updatedTask = {
      ...taskData,
      deadline: newDeadline,
    };

    setTaskData(updatedTask);

    try {
      await updateTask(updatedTask);
    } catch (error) {
      console.error("Failed to update deadline:", error);
      setTaskData((prev) => ({
        ...prev,
        deadline: taskDetails.deadline ?? "",
      }));
      Swal.fire({
        title: "Update Failed",
        text: `Could not update deadline`,
        icon: "error",
      });
    }
  };

  const handleDelete = async () => {
    setShowDropdown(false);
    try {
      await deleteTask(taskDetails.id);
      onClose();
    } catch (error) {
      console.error("Error deleting task:", error);
      Swal.fire("Error!", "Could not delete the task.", "error");
    }
  };

  const handleStatusChange = async (newStatus: string) => {
    const updatedTask = {
      ...taskData,
      status: newStatus,
      columnId: mapStatusToColumnId(newStatus),
    };
    setTaskData(updatedTask);

    try {
      await updateTask(updatedTask);
    } catch (error) {
      console.error("Failed to update status:", error);
      setTaskData(taskData);
      Swal.fire({
        title: "Update Failed",
        text: `Could not update status`,
        icon: "error",
      });
    }
  };

  const handlePriorityChange = async (newPriority: string) => {
    const updatedTask = {
      ...taskData,
      priority: newPriority,
    };

    setTaskData(updatedTask);

    try {
      await updateTask(updatedTask);
    } catch (error) {
      console.error("Failed to update priority:", error);
      setTaskData(taskData);
      Swal.fire({
        title: "Update Failed",
        text: `Could not update priority`,
        icon: "error",
      });
    }
  };

  const mapStatusToColumnId = (status: string): string => {
    if (columns.length > 0) {
      const col = columns.find(c => c.title === status);
      if (col) return col.id;
    }
    
    switch (status) {
      case "To Do":
        return "todo";
      case "In Progress":
        return "progress";
      case "Checks":
        return "check";
      case "Completed":
        return "done";
      default:
        return "todo";
    }
  };

  useEffect(() => {
    const currentDescription = taskDetails.description ?? "";
    setEditedTitle(taskDetails.title);
    setEditedDescription(currentDescription);
    setTaskData({
      ...taskDetails,
      priority: taskDetails.priority || "Medium",
      description: currentDescription,
      deadline: taskDetails.deadline ?? "",
    });
    setIsEditingTitle(false);
    setIsEditingDescription(false);
    setShowDropdown(false);
  }, [taskDetails]);

  const closeModal = () => {
    if (onClose) onClose();
  };

  const startEditingTitle = () => {
    setIsEditingTitle(true);
  };

  const saveTitle = () => {
    if (editedTitle.trim() && editedTitle !== taskData.title) {
      updateTaskField("title", editedTitle.trim());
    } else if (!editedTitle.trim()) {
      setEditedTitle(taskData.title);
    }
    setIsEditingTitle(false);
  };

  const handleTitleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      saveTitle();
    } else if (e.key === "Escape") {
      setEditedTitle(taskData.title);
      setIsEditingTitle(false);
    }
  };

  const startEditingDescription = () => {
    setIsEditingDescription(true);
  };

  const handleSaveDescription = () => {
    if (editedDescription !== taskData.description) {
      updateTaskField("description", editedDescription);
    }
    setIsEditingDescription(false);
  };

  const handleCancelDescription = () => {
    setEditedDescription(taskData.description);
    setIsEditingDescription(false);
  };

  const toggleDropdown = () => {
    setShowDropdown((prev) => !prev);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-lg p-6 md:p-8 max-h-[90vh] w-full h-[80%] max-w-5xl shadow-xl relative flex flex-col overflow-hidden ">
        <div className="flex justify-between items-start mb-4 border-b border-gray-400">
          <p className="text-dark dark:text-light text-sm uppercase tracking-wide">
            {projectName} / TASK-{taskDetails.id}
          </p>

          <div className="flex items-center space-x-2">
            <div className="relative">
              <button
                className="p-2 rounded-md text-dark dark:text-light hover:bg-gray-500 dark:hover:bg-gray-700"
                aria-label="Options"
                onClick={toggleDropdown}
              >
                <Icon type={"more_horiz"} className="h-5 w-5" />
              </button>
              {showDropdown && (
                <div className="absolute right-0 mt-2 w-40 bg-white dark:bg-gray-700 shadow-lg rounded-md py-1 z-10">
                  <button
                    className="block w-full text-left px-4 py-2 text-sm text-dark dark:text-light hover:bg-gray-500 dark:hover:bg-gray-600"
                    onClick={handleDelete}
                  >
                    Delete
                  </button>
                </div>
              )}
            </div>

            <button
              className="p-2 rounded-md text-dark dark:text-light hover:bg-gray-500 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 dark:focus:ring-offset-gray-800"
              aria-label="Close"
              onClick={closeModal}
            >
              <Icon type={"close"} className="h-5 w-5" />
            </button>
          </div>
        </div>

        <div className="flex-grow grid grid-cols-1 md:grid-cols-3 gap-6 overflow-y-auto pr-2 -mr-2">
          {/* Left Column */}
          <div className="md:col-span-2 space-y-6">
            <div>
              {isEditingTitle ? (
                <TextField
                  value={editedTitle}
                  onChange={setEditedTitle}
                  onBlur={saveTitle}
                  onKeyDown={handleTitleKeyDown}
                />
              ) : (
                <button
                  className="w-full text-left text-dark dark:text-light text-xl font-semibold hover:bg-gray-500 dark:hover:bg-gray-700 rounded px-2 py-1"
                  onClick={startEditingTitle}
                  aria-label="Edit task title"
                >
                  {taskData.title}
                </button>
              )}
            </div>

            <div className="mt-4">
              <label
                htmlFor="task-description"
                className="block text-dark dark:text-light font-medium text-base mb-2"
              >
                Description
              </label>
              {isEditingDescription ? (
                <>
                  <CustomTextArea
                    placeholder="Add a more detailed description..."
                    value={editedDescription}
                    onInput={setEditedDescription}
                  />
                  <div className="flex space-x-2 mt-2">
                    <Button
                      text="Save"
                      onClick={handleSaveDescription}
                      style="primary"
                    />

                    <Button
                      text="Cancel"
                      onClick={handleCancelDescription}
                      style="secondary"
                    />
                  </div>
                </>
              ) : (
                <div
                  className="w-full min-h-[80px] p-3 text-sm rounded border border-transparent hover:border-gray-300 dark:hover:border-gray-600 cursor-text whitespace-pre-wrap dark:text-light"
                  onClick={startEditingDescription}
                  role="button"
                  tabIndex={0}
                  onKeyPress={(e) => {
                    if (e.key === "Enter" || e.key === " ")
                      startEditingDescription();
                  }}
                  aria-label="Edit description"
                >
                  {taskData.description ? (
                    taskData.description
                  ) : (
                    <span className="text-gray-300">
                      Add a more detailed description...
                    </span>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Right Column */}
          <div className="border border-gray-300 dark:border-gray-600 md:col-span-1 space-y-6 rounded-md h-fit">
            <div className="p-4">
              <h3 className="text-dark dark:text-light font-semibold mb-8">
                Details
              </h3>
              <div className="space-y-5">
                <Dropdown
                  key={`status-${taskData.id}`}
                  items={statusOptions}
                  selectedItem={taskData.status}
                  onSelect={handleStatusChange}
                  label="Status"
                  width="full"
                />

                <Dropdown
                  key={`priority-${taskData.id}`}
                  items={priorityOptions}
                  selectedItem={taskData.priority}
                  onSelect={handlePriorityChange}
                  label="Priority"
                  width="full"
                />

                <Dropdown
                  key={`deadline-${taskData.id}`}
                  items={[]}
                  selectedItem={taskData.deadline || "Set deadline"}
                  onSelect={handleDeadlineChange}
                  label="Deadline"
                  width="full"
                  isDatePicker={true}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TaskModal;
