// src/components/ui/Dropdown/DropdownLarge.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';

	export let items: string[] = [];
	export let selectedItem: string = '';
	export let type: string = '';
	export let label: string = '';
	export let width: 'full' | 'half' | 'auto' = 'auto';

	const dispatch = createEventDispatcher();

	let isOpen = false;

	const toggleDropdown = () => {
		isOpen = !isOpen;
	};

	const selectItem = (item: string) => {
		selectedItem = item;
		isOpen = false;
		dispatch('select', { item });
	};

	$: displayLabel = type === 'form' && !selectedItem ? 'Please Select' : selectedItem;
</script>

<div>
	{#if label}
		<!-- svelte-ignore a11y_label_has_associated_control -->
		<label class="block mb-1 text-sm font-medium text-dark dark:text-light">{label}</label>
	{/if}

	<div
		class={`relative inline-block text-left ${
			type === 'form' ? 'border border-gray-300 rounded-md' : ''
		} ${width === 'full' ? 'w-full' : width === 'half' ? 'w-1/2' : 'w-auto'}`}
	>
		<!-- Selected Item Button -->
		<button
			class="flex text-dark dark:text-light items-center justify-between px-4 py-2 text-sm hover:underline w-full"
			onclick={toggleDropdown}
			type="button"
		>
			{displayLabel}
			<svg
				xmlns="http://www.w3.org/2000/svg"
				class="w-5 h-5 ml-2 -mr-1 text-gray-300"
				viewBox="0 0 20 20"
				fill="currentColor"
			>
				<path
					fill-rule="evenodd"
					d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
					clip-rule="evenodd"
				/>
			</svg>
		</button>

		<!-- Dropdown Menu -->
		{#if isOpen}
			<ul
				class="absolute z-10 mt-2 bg-white dark:bg-dark rounded-md shadow-lg text-center max-h-40 overflow-y-auto w-full"
			>
				<!-- svelte-ignore a11y_click_events_have_key_events -->
				{#each items as item}
					<!-- svelte-ignore a11y_click_events_have_key_events -->
					<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
					<li
						class="px-4 py-2 text-dark dark:text-light text-sm font-medium cursor-pointer hover:bg-gray-400 dark:hover:bg-dark-100"
						onclick={() => selectItem(item)}
					>
						{item}
					</li>
				{/each}
			</ul>
		{/if}
	</div>
</div>

<style>
	.max-h-40 {
		max-height: 10rem;
	}

	.overflow-y-auto {
		overflow-y: auto;
	}
</style>

// apps/admin/src/components/ui/Dropdown/DropdownLarge.tsx
import { Icon } from "@graminate/ui";
import { useState, useRef, useEffect } from "react";

type Props = {
  items: string[];
  selectedItem: string;
  onSelect: (item: string) => void;
  type?: "form" | "";
  label?: string;
  width?: "full" | "half" | "auto";
  isDatePicker?: boolean;
};

const DropdownLarge = ({
  items,
  selectedItem,
  onSelect,
  type = "",
  label = "",
  width = "auto",
  isDatePicker = false,
}: Props) => {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement | null>(null);

  const toggleDropdown = () => {
    setIsOpen(!isOpen);
  };

  const selectItem = (item: string) => {
    onSelect(item);
    setIsOpen(false);
  };

  const displayLabel =
    type === "form" && !selectedItem ? "Please Select" : selectedItem;

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setIsOpen(false);
      }
    };

    document.addEventListener("click", handleClickOutside);
    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  }, []);

  if (isDatePicker) {
    return (
      <div className="w-full">
        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
          {label}
        </label>
        <input
          type="date"
          value={selectedItem === "Set deadline" ? "" : selectedItem}
          onChange={(e) => onSelect(e.target.value)}
          className="w-full p-2 border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-dark dark:text-light"
        />
      </div>
    );
  }

  return (
    <div>
      {label && (
        <label className="block mb-1 text-sm font-medium text-gray-200 dark:text-gray-300">
          {label}
        </label>
      )}

      <div
        ref={dropdownRef}
        className={`relative inline-block text-left ${
          type === "form" ? "border border-gray-300 rounded-md" : ""
        } ${
          width === "full" ? "w-full" : width === "half" ? "w-1/2" : "w-auto"
        }`}
      >
        {/* Selected Item Button */}
        <button
          className="flex text-dark dark:text-light items-center justify-between px-4 py-2 text-sm w-full"
          onClick={toggleDropdown}
          type="button"
        >
          {displayLabel}
          <Icon
            type={"expand_more" as any}
            className="size-5 ml-2 -mr-1 text-gray-300"
          />
        </button>

        {/* Dropdown Menu */}
        {isOpen && (
          <ul className="absolute z-10 mt-2 bg-white dark:bg-dark rounded-md shadow-lg text-center max-h-40 overflow-y-auto w-full">
            {items.map((item) => (
              <li
                key={item}
                className="px-4 py-2 text-dark dark:text-light text-sm font-medium cursor-pointer hover:bg-gray-400 dark:hover:bg-dark-100"
                onClick={() => selectItem(item)}
              >
                {item}
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
};

export default DropdownLarge;
