// src/components/ui/Switch/TicketView.svelte
<script lang="ts">
	export let isListView: boolean;
	export let toggleView: (view: boolean) => void;
</script>

<div class="flex items-center space-x-2 hover:bg-gray-400 rounded-md">
	<!-- Kanban View Icon -->
	<button
		class="p-2 focus:outline-none focus:bg-green-400 focus:text-green-700"
		on:click={() => {
			if (isListView) {
				toggleView(false);
			}
		}}
		aria-label="Switch to Kanban View"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width="1.5"
			stroke="currentColor"
			class="size-6"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="M6 6.878V6a2.25 2.25 0 0 1 2.25-2.25h7.5A2.25 2.25 0 0 1 18 6v.878m-12 0c.235-.083.487-.128.75-.128h10.5c.263 0 .515.045.75.128m-12 0A2.25 2.25 0 0 0 4.5 9v.878m13.5-3A2.25 2.25 0 0 1 19.5 9v.878m0 0a2.246 2.246 0 0 0-.75-.128H5.25c-.263 0 .515.045.75.128m15 0A2.25 2.25 0 0 1 21 12v6a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 18v-6c0-.98.626-1.813 1.5-2.122"
			/>
		</svg>
	</button>

	<!-- List View Icon -->
	<button
		class="p-2 focus:outline-none focus:bg-green-400 focus:text-green-700"
		on:click={() => {
			if (!isListView) {
				toggleView(true);
			}
		}}
		aria-label="Switch to List View"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width="1.5"
			stroke="currentColor"
			class="size-6"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="M8.25 6.75h12M8.25 12h12m-12 5.25h12M3.75 6.75h.007v.008H3.75V6.75Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0ZM3.75 12h.007v.008H3.75V12Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm-.375 5.25h.007v.008H3.75v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"
			/>
		</svg>
	</button>
</div>

// apps/frontend/src/components/ui/Switch/TicketView.tsx
import { Icon } from "@graminate/ui";
import React from "react";

type TicketViewProps = {
  isListView: boolean;
  toggleView: (view: boolean) => void;
};

const TicketView = ({ isListView, toggleView }: TicketViewProps) => {
  return (
    <div className="flex items-center space-x-2 hover:bg-gray-400 dark:hover:bg-gray-800 rounded-md">
      {/* Kanban View Icon */}
      <button
        className="p-2 focus:outline-none dark:focus:bg-gray-700 focus:bg-gray-300 focus:text-dark dark:focus:text-light rounded-l-md"
        onClick={() => {
          if (isListView) {
            toggleView(false);
          }
        }}
        aria-label="Switch to Kanban View"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth="1.5"
          stroke="currentColor"
          className="size-6"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M6 6.878V6a2.25 2.25 0 0 1 2.25-2.25h7.5A2.25 2.25 0 0 1 18 6v.878m-12 0c.235-.083.487-.128.75-.128h10.5c.263 0 .515.045.75.128m-12 0A2.25 2.25 0 0 0 4.5 9v.878m13.5-3A2.25 2.25 0 0 1 19.5 9v.878m0 0a2.246 2.246 0 0 0-.75-.128H5.25c-.263 0 .515.045.75.128m15 0A2.25 2.25 0 0 1 21 12v6a2.25 2.25 0 0 1-2.25 2.25H5.25A2.25 2.25 0 0 1 3 18v-6c0-.98.626-1.813 1.5-2.122"
          />
        </svg>
      </button>

      {/* List View Icon */}
      <button
        className="p-2 focus:outline-none dark:focus:bg-gray-700 focus:bg-gray-300 focus:text-dark dark:focus:text-light rounded-r-md"
        onClick={() => {
          if (!isListView) {
            toggleView(true);
          }
        }}
        aria-label="Switch to List View"
      >
        <Icon type={"list" as any} className="size-6" />
      </button>
    </div>
  );
};

export default TicketView;
