// src/components/ui/SearchBar.svelte
<script lang="ts">
	export let query: string = '';
	export let placeholder: string = '';
	export let mode: string = '';

	if (mode === 'table' && !placeholder) {
		throw new Error("The 'placeholder' parameter is mandatory when 'mode' is set to 'table'.");
	}

	if (mode === 'type' && !placeholder) {
		placeholder = 'Search';
	}

	const handleSearch = () => {
		dispatchSearchEvent();
	};

	const handleKeyDown = (event: KeyboardEvent) => {
		if (event.key === 'Enter') {
			handleSearch();
		}
	};

	const dispatchSearchEvent = () => {
		const searchEvent = new CustomEvent('search', {
			detail: query
		});
		dispatchEvent(searchEvent);
	};
</script>

<div class="relative">
	<input
		type="text"
		bind:value={query}
		{placeholder}
		class="w-full px-4 py-1 border border-gray-300 dark:border-gray-200 focus:border-green-200 rounded-md dark:bg-dark-100 focus:outline-none dark:text-gray-500"
		onkeydown={handleKeyDown}
	/>
	<button
		class="absolute inset-y-0 right-4 flex items-center"
		onclick={handleSearch}
		aria-label="Search"
	>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width="1.5"
			stroke="currentColor"
			class="size-5 stroke-gray-800 dark:stroke-white"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z"
			/>
		</svg>
	</button>
</div>

// packages/ui/lib/components/searchbar.tsx
import { Icon } from "./icon";
import React from "react";
import { cn } from "../utils";

type Props = {
  value: string;
  placeholder?: string;
  mode?: "table" | "type";
  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  className?: string;
};

const SearchBar = ({ value, placeholder = "", mode, onChange, className }: Props) => {
  if (mode === "table" && !placeholder) {
    throw new Error(
      "The 'placeholder' parameter is mandatory when 'mode' is set to 'table'."
    );
  }

  if (mode === "type" && !placeholder) {
    placeholder = "Search";
  }

  return (
    <div className={cn("relative", className)}>
      <input
        type="text"
        value={value}
        placeholder={placeholder}
        className="w-full px-4 py-2 border border-neutral-200 dark:border-gray-200 focus:border-brand-mute-green 
                   rounded-lg dark:bg-gray-700 focus:outline-none 
                   text-neutral-900 dark:text-neutral-100 placeholder-neutral-400 dark:placeholder-neutral-600 shadow-sm transition-all"
        onChange={onChange}
      />
      <button
        className="absolute inset-y-0 right-4 flex items-center hover:scale-110 transition-transform"
        aria-label="Search"
      >
        <Icon
          type={"search"}
          className="size-5 text-neutral-500 dark:text-neutral-400"
        />
      </button>
    </div>
  );
};

export { SearchBar };
