// apps/website/src/components/cards/company/JobCard.tsx
import React, { useState } from "react";
import { Button } from "@graminate/ui";

interface JobCardProps {
  position: string;
  type: string;
  mode: string;
  description: string;
  tasks?: string[];
  requirements?: string[];
  benefits?: string[];
  jobpost: string;
}
const JobCard: React.FC<JobCardProps> = ({
  position,
  type,
  mode,
  description,
  tasks = [],
  requirements = [],
  benefits = [],
  jobpost,
}) => {
  const [showDetails, setShowDetails] = useState(false);
  // const router = useRouter();

  const applyForJob = () => {
    window.open(jobpost, "_blank");
  };

  // const applyForJob = () => {
  //   const formattedPosition = position.toLowerCase().replace(/\s+/g, "-");
  //   const formattedType = type.toLowerCase().replace(/\s+/g, "-");
  //   const formattedMode = mode.toLowerCase().replace(/\s+/g, "-");

  //   router.push(
  //     `/company/${formattedPosition}?type=${formattedType}&mode=${formattedMode}`
  //   );
  // };

  return (
    <div className="flex flex-col rounded-lg bg-white p-6 shadow-md">
      <div className="flex items-center justify-between">
        <h3 className="text-xl font-semibold text-gray-900">{position}</h3>
        <Button label="Apply" variant="primary" onClick={applyForJob} />
      </div>
      <p className="text-sm text-gray-600">
        {type} ⋅ {mode}
      </p>
      <p className="mt-2">{description}</p>

      {/* Show More / Show Less Toggle */}
      <button
        className="mt-2 text-blue-600 hover:underline focus:outline-none"
        onClick={() => setShowDetails(!showDetails)}
      >
        {showDetails ? "Show less" : "Show more"}
      </button>

      {showDetails && (
        <>
          {tasks.length > 0 && (
            <div className="mt-4">
              <h4 className="text-lg font-semibold text-gray-800">Tasks</h4>
              <ul className="list-inside list-disc text-gray-600">
                {tasks.map((task, index) => (
                  <li key={index}>{task}</li>
                ))}
              </ul>
            </div>
          )}

          {requirements.length > 0 && (
            <div className="mt-4">
              <h4 className="text-lg font-semibold text-gray-800">
                Requirements
              </h4>
              <ul className="list-inside list-disc text-gray-600">
                {requirements.map((requirement, index) => (
                  <li key={index}>{requirement}</li>
                ))}
              </ul>
            </div>
          )}

          {benefits.length > 0 && (
            <div className="mt-4">
              <h4 className="text-lg font-semibold text-gray-800">Benefits</h4>
              <ul className="list-inside list-disc text-gray-600">
                {benefits.map((benefit, index) => (
                  <li key={index}>{benefit}</li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default JobCard;

// src/components/cards/JobCard.svelte
<script lang="ts">
	import Button from '@ui/Button.svelte';
	import { goto } from '$app/navigation';

	export let position: string;
	export let type: string;
	export let mode: string;
	export let description: string;
	export let tasks: string[] = [];
	export let requirements: string[] = [];
	export let benefits: string[] = [];

	let showDetails = false;

	const applyForJob = () => {
		const formattedPosition = position.toLowerCase().replace(/\s+/g, '-'); // URL-friendly format
		const formattedType = type.toLowerCase().replace(/\s+/g, '-');
		const formattedMode = mode.toLowerCase().replace(/\s+/g, '-');

		goto(`/career/${formattedPosition}?type=${formattedType}&mode=${formattedMode}`);
	};
</script>

<div class="bg-white p-6 rounded-lg shadow-md flex flex-col">
	<div class="flex justify-between items-center">
		<h3 class="text-xl font-semibold text-gray-900">{position}</h3>
		<Button text="Apply" style="primary" on:click={applyForJob} />
	</div>
	<p class="text-gray-200 text-sm">{type} ⋅ {mode}</p>
	<p class="mt-2">{description}</p>

	<!-- Show More / Show Less Toggle -->
	<button
		class="mt-2 text-blue-600 hover:underline focus:outline-none"
		on:click={() => (showDetails = !showDetails)}
	>
		{showDetails ? 'Show less' : 'Show more'}
	</button>

	{#if showDetails}
		{#if tasks.length}
			<div class="mt-4">
				<h4 class="text-lg font-semibold text-gray-800">Tasks</h4>
				<ul class="list-disc list-inside text-gray-600">
					{#each tasks as task}
						<li>{task}</li>
					{/each}
				</ul>
			</div>
		{/if}

		{#if requirements.length}
			<div class="mt-4">
				<h4 class="text-lg font-semibold text-gray-800">Requirements</h4>
				<ul class="list-disc list-inside text-gray-600">
					{#each requirements as requirement}
						<li>{requirement}</li>
					{/each}
				</ul>
			</div>
		{/if}

		{#if benefits.length}
			<div class="mt-4">
				<h4 class="text-lg font-semibold text-gray-800">Benefits</h4>
				<ul class="list-disc list-inside text-gray-600">
					{#each benefits as benefit}
						<li>{benefit}</li>
					{/each}
				</ul>
			</div>
		{/if}
	{/if}
</div>
