// apps/website/src/components/cards/company/MembersCard.tsx
import { Icon } from "@graminate/ui";
import Image from "next/image";

interface MembersCardProps {
  avatar: string;
  name: string;
  role: string;
  description: string;
  linkedin?: string;
  github?: string;
  website?: string;
}

const MembersCard: React.FC<MembersCardProps> = ({
  avatar,
  name,
  role,
  description,
  linkedin,
  github,
  website,
}) => {
  return (
    <div className="w-full max-w-sm mx-auto rounded-2xl bg-white shadow-xl transition hover:shadow-2xl">
      <div className="flex flex-col items-center p-6">
        <div className="relative h-32 w-32 rounded-full overflow-hidden shadow-md">
          <Image
            src={avatar}
            alt={`${name}'s avatar`}
            width={128}
            height={128}
            className="object-cover h-full w-full transition-transform duration-300 hover:scale-110"
          />
        </div>

        <div className="text-center mt-4">
          <h3 className="text-lg font-semibold text-dark dark:text-light">
            {name}
          </h3>
          <p className="text-sm text-dark dark:text-light mb-2">{role}</p>
          <p className="text-sm text-dark dark:text-light">{description}</p>
        </div>

        <div className="mt-4 flex space-x-4">
          {linkedin && (
            <a
              href={linkedin}
              aria-label="LinkedIn"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 hover:text-blue-600"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/>
              </svg>
            </a>
          )}
          {github && (
            <a
              href={github}
              aria-label="GitHub"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 hover:text-black"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.042-1.416-4.042-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
            </a>
          )}
          {website && (
            <a
              href={website}
              aria-label="Website"
              target="_blank"
              rel="noopener noreferrer"
              className="text-gray-400 hover:text-blue-500"
            >
              <Icon type="public" className="size-5" />
            </a>
          )}
        </div>
      </div>
    </div>
  );
};

export default MembersCard;

// src/components/cards/MembersCard.svelte
<script lang="ts">
	import linkedinIcon from '@icons/social/linkedin.svg';
	import githubIcon from '@icons/social/github.svg';
	import webIcon from '@icons/social/web.svg';
	export let avatar: string;
	export let name: string;
	export let role: string;
	export let description: string;
	export let linkedin: string;
	export let github: string;
	export let website: string;
</script>

<div class="container mx-auto">
	<div class="max-w-xl rounded overflow-hidden shadow-lg bg-white py-10 px-5">
		<div class="h-48 w-48 mx-auto rounded-full flex items-center justify-center overflow-hidden">
			<img
				class="hover:scale-125 transition-all duration-500 cursor-pointer w-full h-full object-cover"
				src={avatar}
				alt="Avatar"
			/>
		</div>

		<div class="px-6 py-4 text-center">
			<p class="text-normal text-gray-200 font-bold pt-2 transition-colors duration-300">
				{name}
			</p>
			<p class="font-semibold text-gray-200 text-sm mb-3">
				{role}
			</p>
			<p class="max-w-md mx-auto text-sm lg:text-gray-800">
				{description}
			</p>

			<div class="mt-10 flex justify-center space-x-4">
				{#if linkedin}
					<a href={linkedin} aria-label="Linkedin" target="_blank">
						<img src={linkedinIcon} alt="Linkedin" class="w-5 h-5" />
					</a>
				{/if}
				{#if github}
					<a href={github} target="_blank">
						<img src={githubIcon} alt="GitHub" class="w-5 h-5" />
					</a>
				{/if}
				{#if website}
					<a href={website} aria-label="website" target="_blank">
						<img src={webIcon} alt="GitHub" class="w-5 h-5" />
					</a>
				{/if}
			</div>
		</div>
	</div>
</div>
