// apps/frontend/src/components/cards/weather/SunCard.tsx
import { Icon } from "@graminate/ui";
import React, { useState, useEffect, useRef, useCallback } from "react";
import { Coordinates } from "@/types/card-props";
import axios from "axios";
import Loader from "@/components/ui/Loader";
import { useDisplayMode, useWeatherData } from "@/hooks/weather";
import { useUserPreferences } from "@/contexts/UserPreferencesContext";

type DailySunData = {
  time: string[];
  daylightDuration: number[];
};

const SunCard = ({ lat, lon }: Coordinates) => {
  const { timeFormat } = useUserPreferences();

  const [sunriseTime, setSunriseTime] = useState<string | null>(null);
  const [sunsetTime, setSunsetTime] = useState<string | null>(null);

  const [sunTimesArray, setSunTimesArray] = useState<
    { date: string; sunrise: string; sunset: string }[]
  >([]);
  const [currentXSun, setCurrentXSun] = useState<number>(0);
  const [currentYSun, setCurrentYSun] = useState<number>(0);
  const [hoverXSun, setHoverXSun] = useState<number>(0);
  const [hoverYSun, setHoverYSun] = useState<number>(0);
  const [isHovering, setIsHovering] = useState<boolean>(false);
  const [hoveredTime, setHoveredTime] = useState<string | null>(null);
  const [displayedSunsetTime, setDisplayedSunsetTime] = useState<string | null>(
    null
  );
  const [sunsetLabel, setSunsetLabel] = useState<string>("");
  const { displayMode, dropdownOpen, toggleDropdown, selectDisplayMode } =
    useDisplayMode<"Small" | "Large">({ initialMode: "Small" });

  const fetchSunApiData = useCallback(
    async (
      latitude: number,
      longitude: number
    ): Promise<DailySunData | null> => {
      const response = await axios.get("/api/weather", {
        params: {
          lat: latitude,
          lon: longitude,
        },
      });
      if (
        response.data &&
        response.data.daily &&
        response.data.daily.time &&
        response.data.daily.daylightDuration
      ) {
        return response.data.daily as DailySunData;
      }
      return null;
    },
    []
  );

  const {
    data: dailySunData,
    isLoading: isSunDataLoading,
    error: sunDataError,
  } = useWeatherData<DailySunData>({
    fetchFunction: fetchSunApiData,
    lat,
    lon,
  });

  const svgRef = useRef<SVGSVGElement | null>(null);

  const parseTimeToMinutes = useCallback((time: string): number => {
    if (!time || !time.includes(":")) return 0;
    const parts = time.split(":");
    let h = parseInt(parts[0], 10);
    const mString = parts[1].replace(/[^0-9]/g, "");
    const m = parseInt(mString, 10);

    if (isNaN(h) || isNaN(m)) return 0;

    const isPM = time.toLowerCase().includes("pm");
    const isAM = time.toLowerCase().includes("am");

    if (isPM && h < 12) {
      h += 12;
    } else if (isAM && h === 12) {
      h = 0;
    }
    return h * 60 + m;
  }, []);

  const formatTimeFromMinutes = useCallback(
    (minutes: number): string => {
      const date = new Date();
      date.setHours(
        Math.floor(minutes / 60) % 24,
        Math.floor(minutes % 60),
        0,
        0
      );
      return date.toLocaleTimeString(undefined, {
        hour: "2-digit",
        minute: "2-digit",
        hour12: timeFormat === "12-hour",
      });
    },
    [timeFormat]
  );

  const formatDuration = (minutes: number): string => {
    if (minutes < 0) minutes = 0;
    const hrs = Math.floor(minutes / 60);
    const mins = Math.round(minutes % 60);
    return `${hrs}h ${mins}m`;
  };

  const calculateAndFormatSunriseSunset = useCallback(
    (
      daylightSeconds: number
    ): {
      sunrise: string;
      sunset: string;
    } => {
      if (isNaN(daylightSeconds) || daylightSeconds <= 0) {
        return { sunrise: "--:--", sunset: "--:--" };
      }
      const daylightHours = daylightSeconds / 3600;
      const halfDaylight = daylightHours / 2;
      const solarNoonMinutes = 12 * 60;
      const sunriseMinutes = solarNoonMinutes - halfDaylight * 60;
      const sunsetMinutes = solarNoonMinutes + halfDaylight * 60;
      return {
        sunrise: formatTimeFromMinutes(sunriseMinutes),
        sunset: formatTimeFromMinutes(sunsetMinutes),
      };
    },
    [formatTimeFromMinutes]
  );

  const calculateSunPosition = (t: number): { x: number; y: number } => {
    const clampedT = Math.max(0, Math.min(1, t));
    const pathWidth = 160;
    const pathHeight = 50;
    const midPointX = pathWidth / 2;
    const p0x = 0,
      p0y = pathHeight;
    const p1x = midPointX,
      p1y = 0;
    const p2x = pathWidth,
      p2y = pathHeight;
    const currentX =
      Math.pow(1 - clampedT, 2) * p0x +
      2 * (1 - clampedT) * clampedT * p1x +
      Math.pow(clampedT, 2) * p2x;
    const currentY =
      Math.pow(1 - clampedT, 2) * p0y +
      2 * (1 - clampedT) * clampedT * p1y +
      Math.pow(clampedT, 2) * p2y;
    return { x: currentX, y: currentY - 1 };
  };

  useEffect(() => {
    if (dailySunData) {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      let startIndex = dailySunData.time.findIndex((dateStr: string) => {
        const date = new Date(dateStr);
        date.setHours(0, 0, 0, 0);
        return date >= today;
      });
      if (startIndex === -1) {
        startIndex = 0;
      }
      if (
        dailySunData.daylightDuration &&
        dailySunData.daylightDuration[startIndex] !== undefined &&
        dailySunData.daylightDuration[startIndex] !== null
      ) {
        const { sunrise, sunset } = calculateAndFormatSunriseSunset(
          dailySunData.daylightDuration[startIndex]
        );
        setSunriseTime(sunrise);
        setSunsetTime(sunset);
      } else {
        setSunriseTime("--:--");
        setSunsetTime("--:--");
      }
      const arr: { date: string; sunrise: string; sunset: string }[] = [];
      const maxDays = dailySunData.time.length;
      for (let i = startIndex; i < Math.min(startIndex + 7, maxDays); i++) {
        if (
          dailySunData.daylightDuration?.[i] !== undefined &&
          dailySunData.daylightDuration?.[i] !== null &&
          dailySunData.time?.[i]
        ) {
          const { sunrise, sunset } = calculateAndFormatSunriseSunset(
            dailySunData.daylightDuration[i]
          );
          arr.push({
            date: dailySunData.time[i],
            sunrise,
            sunset,
          });
        }
      }
      setSunTimesArray(arr);
    }
  }, [dailySunData, calculateAndFormatSunriseSunset]);

  useEffect(() => {
    if (
      sunriseTime &&
      sunsetTime &&
      sunriseTime !== "--:--" &&
      sunsetTime !== "--:--"
    ) {
      const now = new Date();
      const currentMinutes = now.getHours() * 60 + now.getMinutes();
      const sunriseMins = parseTimeToMinutes(sunriseTime);
      const sunsetMins = parseTimeToMinutes(sunsetTime);
      if (sunsetMins <= sunriseMins) {
        setCurrentXSun(0);
        setCurrentYSun(50);
        return;
      }
      const t = (currentMinutes - sunriseMins) / (sunsetMins - sunriseMins);
      const { x, y } = calculateSunPosition(t);
      setCurrentXSun(x);
      setCurrentYSun(y);
    } else {
      setCurrentXSun(0);
      setCurrentYSun(50);
    }
  }, [sunriseTime, sunsetTime, parseTimeToMinutes]);

  useEffect(() => {
    if (displayMode === "Large" && sunTimesArray.length > 0) {
      const now = new Date();
      const currentMinutes = now.getHours() * 60 + now.getMinutes();
      let displayIndex = 0;
      const todaysSunsetMinutes = parseTimeToMinutes(sunTimesArray[0]?.sunset);
      if (
        sunTimesArray[0]?.sunset &&
        currentMinutes >= todaysSunsetMinutes &&
        sunTimesArray.length > 1
      ) {
        displayIndex = 1;
        setSunsetLabel("Sunset Tomorrow");
      } else if (sunTimesArray[0]?.sunset) {
        setSunsetLabel("Sunset Today");
      } else {
        setSunsetLabel("Sunset");
      }
      setDisplayedSunsetTime(sunTimesArray[displayIndex]?.sunset || "--:--");
    }
  }, [displayMode, sunTimesArray, parseTimeToMinutes]);

  const handleMouseMove = (event: React.MouseEvent<SVGSVGElement>) => {
    if (
      !svgRef.current ||
      !sunriseTime ||
      !sunsetTime ||
      sunriseTime === "--:--" ||
      sunsetTime === "--:--"
    )
      return;
    const svg = svgRef.current;
    const pt = svg.createSVGPoint();
    pt.x = event.clientX;
    pt.y = event.clientY;
    const svgP = pt.matrixTransform(svg.getScreenCTM()?.inverse());
    const relativeX = svgP.x;
    const viewBoxWidth = 160;
    let t = relativeX / viewBoxWidth;
    t = Math.max(0, Math.min(1, t));
    const sunriseMins = parseTimeToMinutes(sunriseTime);
    const sunsetMins = parseTimeToMinutes(sunsetTime);
    if (sunsetMins > sunriseMins) {
      const hoveredMinutes = sunriseMins + t * (sunsetMins - sunriseMins);
      setHoveredTime(formatTimeFromMinutes(hoveredMinutes));
      const { x, y } = calculateSunPosition(t);
      setHoverXSun(x);
      setHoverYSun(y);
      setIsHovering(true);
    }
  };

  const handleMouseLeave = () => {
    setIsHovering(false);
    setHoveredTime(null);
  };

  const displayXSun = isHovering ? hoverXSun : currentXSun;
  const displayYSun = isHovering ? hoverYSun : currentYSun;

  return (
    <div className="p-4 rounded-lg shadow-md max-w-sm mx-auto flex flex-col items-center relative dark:bg-gray-700 bg-gray-500">
      <div className="absolute top-2 right-2 z-10">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          strokeWidth="1.5"
          stroke="currentColor"
          className="w-6 h-6 cursor-pointer text-dark dark:text-light"
          onClick={toggleDropdown}
          onKeyDown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              toggleDropdown();
              e.preventDefault();
            }
          }}
          tabIndex={0}
          role="button"
          aria-label="Toggle dropdown"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M6.75 12a.75.75 0 111.5 0 .75.75 0 01-1.5 0zM12.75 12a.75.75 0 111.5 0 .75.75 0 01-1.5 0zM18.75 12a.75.75 0 111.5 0 .75.75 0 01-1.5 0z"
          />
        </svg>
        {dropdownOpen && (
          <div className="absolute top-8 right-0 bg-white dark:bg-gray-600 dark:text-light text-black rounded-lg shadow-lg z-20 w-32">
            <button
              className="w-full text-left text-sm px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-800 rounded-t-lg cursor-pointer"
              type="button"
              onClick={() => selectDisplayMode("Small")}
            >
              Small
            </button>
            <button
              className="w-full text-left text-sm px-4 py-2 hover:bg-gray-400 dark:hover:bg-gray-800 rounded-b-lg cursor-pointer"
              type="button"
              onClick={() => selectDisplayMode("Large")}
            >
              Large
            </button>
          </div>
        )}
      </div>
      {sunDataError ? (
        <p className="text-red-200 text-center py-10">{sunDataError}</p>
      ) : isSunDataLoading ? (
        <p className="text-center py-10 text-dark dark:text-light">
          <Loader />
        </p>
      ) : dailySunData ? (
        <>
          {displayMode === "Small" &&
            sunriseTime !== null &&
            sunsetTime !== null && (
              <div
                className={`w-full ${displayMode === "Small" ? "pb-8" : ""}`}
              >
                <div className="flex flex-col items-center w-full text-center rounded-md">
                  <div className="w-full flex flex-row items-center justify-center mb-2 gap-2">
                    <Icon
                      type={"light_mode"}
                      className="w-4 h-4 text-yellow-200"
                    />
                    <p className="text-sm uppercase tracking-wide text-gray-200 dark:text-light">
                      Sunrise & Sunset
                    </p>
                  </div>
                  <div className="w-full grid grid-cols-2 gap-2 text-center mb-1 px-2">
                    <div>
                      <p className="text-xs tracking-wide text-dark dark:text-light">
                        Sunrise
                      </p>
                      <p className="text-lg font-semibold text-dark dark:text-light">
                        {sunriseTime}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs tracking-wide text-dark dark:text-light">
                        Sunset
                      </p>
                      <p className="text-lg font-semibold text-dark dark:text-light">
                        {sunsetTime}
                      </p>
                    </div>
                  </div>
                  <div className="h-4">
                    {isHovering && hoveredTime && (
                      <p className="text-center text-md text-dark dark:text-light font-bold">
                        {hoveredTime}
                      </p>
                    )}
                  </div>
                  <div
                    className="relative w-full max-w-2/3 mx-auto cursor-crosshair"
                    onMouseLeave={handleMouseLeave}
                  >
                    <svg
                      ref={svgRef}
                      viewBox="0 0 160 55"
                      className="w-full h-auto overflow-visible"
                      onMouseMove={handleMouseMove}
                    >
                      <path
                        d="M0,50 H160 V55 H0 Z"
                        className="fill-gray-600 dark:fill-gray-800"
                      />
                      <path
                        d="M0,50 Q80,0 160,50"
                        className="stroke-gray-300 dark:stroke-gray-500"
                        strokeWidth="1"
                        fill="none"
                        strokeDasharray="2,2"
                      />
                      <line
                        x1="0"
                        y1="50"
                        x2="160"
                        y2="50"
                        className="stroke-gray-500 dark:stroke-gray-600"
                        strokeWidth="1.5"
                      />
                      <g
                        transform={`translate(${displayXSun}, ${displayYSun})`}
                      >
                        <circle
                          cx="0"
                          cy="0"
                          r="5"
                          className={
                            displayYSun >= 49
                              ? "fill-gray-200 dark:fill-gray-200"
                              : "fill-yellow-200"
                          }
                        />
                        {displayYSun < 49 &&
                          Array.from({ length: 8 }).map((_, i) => {
                            const angle = (i * 45 * Math.PI) / 180;
                            return (
                              <line
                                key={i}
                                x1={Math.cos(angle) * 6}
                                y1={Math.sin(angle) * 6}
                                x2={Math.cos(angle) * 8}
                                y2={Math.sin(angle) * 8}
                                className="stroke-yellow-200"
                                strokeWidth="1.5"
                              />
                            );
                          })}
                      </g>
                    </svg>
                  </div>
                </div>
              </div>
            )}
          {displayMode === "Large" && sunTimesArray.length > 0 && (
            <div className="w-full flex flex-col">
              {displayedSunsetTime && (
                <div className="text-center mb-4">
                  <p className="text-sm text-dark dark:text-light">
                    {sunsetLabel}
                  </p>
                  <p className="text-3xl font-semibold text-gray-100 dark:text-light mt-1">
                    {displayedSunsetTime}
                  </p>
                </div>
              )}
              <div className="w-full space-y-1 border-t border-b border-gray-400 dark:border-gray-600 py-2 mb-3">
                <div className="flex justify-between items-center">
                  <span className="text-xs text-dark dark:text-light">
                    First Light
                  </span>
                  <span className="text-sm font-medium text-gray-100 dark:text-light">
                    {formatTimeFromMinutes(
                      Math.max(
                        parseTimeToMinutes(sunTimesArray[0].sunrise) - 30,
                        0
                      )
                    )}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-xs text-dark dark:text-light">
                    Sunrise
                  </span>
                  <span className="text-sm font-medium text-gray-100 dark:text-light">
                    {sunTimesArray[0].sunrise}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-xs text-dark dark:text-light">
                    Sunset
                  </span>
                  <span className="text-sm font-medium text-gray-100 dark:text-light">
                    {sunTimesArray[0].sunset}
                  </span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-xs text-dark dark:text-light">
                    Last Light
                  </span>
                  <span className="text-sm font-medium text-gray-100 dark:text-light">
                    {formatTimeFromMinutes(
                      Math.min(
                        parseTimeToMinutes(sunTimesArray[0].sunset) + 30,
                        1439
                      )
                    )}
                  </span>
                </div>
                <div className="flex justify-between items-center pt-1">
                  <span className="text-xs text-dark dark:text-light">
                    Daylight Duration
                  </span>
                  <span className="text-sm font-medium text-gray-100 dark:text-light">
                    {formatDuration(
                      parseTimeToMinutes(sunTimesArray[0].sunset) -
                        parseTimeToMinutes(sunTimesArray[0].sunrise)
                    )}
                  </span>
                </div>
              </div>
              <p className="text-xs text-center text-dark dark:text-light mb-2">
                Upcoming Days
              </p>
              <div
                className="w-full overflow-y-auto"
                style={{ maxHeight: "160px" }}
              >
                <div className="flex flex-col space-y-1">
                  {sunTimesArray.slice(1).map((sunData, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between gap-2 px-1 py-1 rounded hover:bg-gray-400"
                    >
                      <p className="text-sm font-medium text-dark dark:text-light w-10 text-left">
                        {new Date(sunData.date).toLocaleDateString(undefined, {
                          weekday: "short",
                        })}
                      </p>
                      <p className="text-xs text-dark dark:text-light w-12 text-center">
                        {sunData.sunrise}
                      </p>
                      <div className="flex-1 h-1.5 bg-gray-700 dark:bg-gray-800 rounded-full overflow-hidden mx-2">
                        <div
                          className="h-full bg-yellow-200"
                          style={{
                            marginLeft: `${
                              (parseTimeToMinutes(sunData.sunrise) / 1440) * 100
                            }%`,
                            width: `${Math.max(
                              0,
                              ((parseTimeToMinutes(sunData.sunset) -
                                parseTimeToMinutes(sunData.sunrise)) /
                                1440) *
                                100
                            )}%`,
                          }}
                        />
                      </div>
                      <p className="text-xs text-dark dark:text-light w-12 text-center">
                        {sunData.sunset}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </>
      ) : (
        <div className="text-center py-10 text-dark dark:text-light">
          <p>No sun data available.</p>
        </div>
      )}
    </div>
  );
};

export default SunCard;

// src/components/cards/SunCard.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { writable, get } from 'svelte/store';
	import { FontAwesomeIcon } from '@fortawesome/svelte-fontawesome';
	import { faSun } from '@fortawesome/free-solid-svg-icons';

	export let lat: number | undefined;
	export let lon: number | undefined;

	let sunriseTime: string | null = null;
	let sunsetTime: string | null = null;
	let locationName: string | null = null;
	let error: string | null = null;

	const displayMode = writable('Small');
	let sunTimesArray: { date: string; sunrise: string; sunset: string }[] = [];
	let dailySunData: any = null;

	let dropdownOpen = false;
	let xSun = 0;
	let ySun = 0;

	const apiKey = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;

	function parseTimeToMinutes(time: string): number {
		const [h, m] = time.split(':').map(Number);
		return h * 60 + m;
	}

	function formatTimeFromMinutes(minutes: number): string {
		const hrs = Math.floor(minutes / 60);
		const mins = Math.floor(minutes % 60);
		return `${hrs}:${mins.toString().padStart(2, '0')}`;
	}

	function formatDuration(minutes: number): string {
		const hrs = Math.floor(minutes / 60);
		const mins = minutes % 60;
		return `${hrs}h ${mins}m`;
	}

	async function fetchSunData(latitude: number, longitude: number) {
		try {
			const response = await fetch(`/api/weather?lat=${latitude}&lon=${longitude}`);
			if (!response.ok) {
				throw new Error(`Error fetching sun data: ${response.statusText}`);
			}
			const data = await response.json();
			// Return the full daily object
			return data.daily;
		} catch (err: any) {
			console.error(err.message);
			throw new Error('Failed to fetch sun data');
		}
	}

	async function fetchCityName(latitude: number, longitude: number) {
		try {
			const response = await fetch(
				`https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=${apiKey}`
			);
			if (!response.ok) {
				throw new Error(`Error fetching location data: ${response.statusText}`);
			}
			const data = await response.json();
			const cityComponent = data.results[0]?.address_components.find((component: any) =>
				component.types.includes('locality')
			);
			return cityComponent?.long_name || 'Your Location';
		} catch (err: any) {
			console.error(err.message);
			return 'Unknown city';
		}
	}

	function calculateSunriseSunset(daylightSeconds: number) {
		const daylightHours = daylightSeconds / 3600;
		const halfDaylight = daylightHours / 2;
		const solarNoon = 12 * 60;
		const sunriseMinutes = solarNoon - halfDaylight * 60;
		const sunsetMinutes = solarNoon + halfDaylight * 60;

		function formatTime(minutes: number) {
			const hours = Math.floor(minutes / 60);
			const mins = Math.floor(minutes % 60);
			return `${hours}:${mins.toString().padStart(2, '0')}`;
		}

		return {
			sunrise: formatTime(sunriseMinutes),
			sunset: formatTime(sunsetMinutes)
		};
	}

	// Only fetch data on mount.
	onMount(async () => {
		if (lat !== undefined && lon !== undefined) {
			try {
				const [fetchedDailySunData, city] = await Promise.all([
					fetchSunData(lat, lon),
					fetchCityName(lat, lon)
				]);
				dailySunData = fetchedDailySunData;
				locationName = city;
			} catch (err: any) {
				error = err.message;
			}
		} else {
			error = 'Latitude and Longitude are required to fetch sun data.';
		}
	});

	// Update sun position arc when sunrise and sunset times are available.
	$: if (sunriseTime && sunsetTime) {
		const now = new Date();
		const currentMinutes = now.getHours() * 60 + now.getMinutes();
		const sunriseMins = parseTimeToMinutes(sunriseTime);
		const sunsetMins = parseTimeToMinutes(sunsetTime);
		let fraction = (currentMinutes - sunriseMins) / (sunsetMins - sunriseMins);
		if (isNaN(fraction)) fraction = 0;
		fraction = Math.max(0, Math.min(1, fraction));
		xSun = 100 * fraction;
		ySun = 25 * ((1 - fraction) ** 2 + fraction ** 2);
	}

	// Reactive block for Small displayMode
	$: if (dailySunData && $displayMode === 'Small') {
		const today = new Date().toISOString().split('T')[0];
		let startIndex = dailySunData.time.findIndex((date: string) => date >= today);
		if (startIndex === -1) {
			startIndex = 0;
		}
		const { sunrise, sunset } = calculateSunriseSunset(dailySunData.daylightDuration[startIndex]);
		sunriseTime = sunrise;
		sunsetTime = sunset;
		error = null;
	}

	// Reactive block for Large displayMode
	$: if (dailySunData && $displayMode === 'Large') {
		sunTimesArray = [];
		const today = new Date().toISOString().split('T')[0];
		let startIndex = dailySunData.time.findIndex((date: string) => date >= today);
		if (startIndex === -1) {
			startIndex = 0;
		}
		for (let i = startIndex; i < startIndex + 7; i++) {
			if (dailySunData.daylightDuration[i] !== undefined && dailySunData.time[i] !== undefined) {
				const { sunrise, sunset } = calculateSunriseSunset(dailySunData.daylightDuration[i]);
				sunTimesArray.push({
					date: dailySunData.time[i],
					sunrise,
					sunset
				});
			}
		}
		error = null;
	}
</script>

<div
	class="p-4 rounded-lg shadow-md max-w-sm mx-auto flex flex-col items-center relative
         bg-gradient-to-t from-gray-300 to-gray-200 text-white"
>
	<div class="absolute top-2 right-2 z-10">
		<!-- Dropdown for selecting display mode -->
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width="1.5"
			stroke="currentColor"
			class="w-6 h-6 cursor-pointer"
			onclick={() => (dropdownOpen = !dropdownOpen)}
			onkeydown={(event) => {
				if (event.key === 'Enter' || event.key === ' ') {
					dropdownOpen = !dropdownOpen;
					event.preventDefault();
				}
			}}
			tabindex="0"
			role="button"
			aria-label="Toggle dropdown"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z"
			/>
		</svg>

		{#if dropdownOpen}
			<div
				class="absolute top-8 right-0 bg-white dark:bg-gray-700 dark:text-light text-black
               rounded-lg shadow-lg z-20 w-32"
			>
				<button
					class="w-full text-left text-sm px-4 py-2 hover:bg-gray-500 dark:hover:bg-yellow-100 cursor-pointer"
					type="button"
					onclick={() => {
						$displayMode = 'Small';
						dropdownOpen = false;
					}}
				>
					Small
				</button>
				<button
					class="w-full text-left text-sm px-4 py-2 hover:bg-gray-500 dark:hover:bg-yellow-100 cursor-pointer"
					type="button"
					onclick={() => {
						$displayMode = 'Large';
						dropdownOpen = false;
					}}
				>
					Large
				</button>
			</div>
		{/if}
	</div>

	{#if error}
		<p class="text-red-500 text-center">Error: {error}</p>
	{:else if sunriseTime !== null && sunsetTime !== null}
		{#if $displayMode === 'Small'}
			<div class="flex flex-col items-center justify-center w-[180px] p-1 text-center rounded-md">
				<div class="w-full flex flex-col items-start">
					<div class="flex flex-row items-center gap-2">
						<FontAwesomeIcon icon={faSun} class="size-5 text-gray-400" />
						<p class="text-lg tracking-wide">Sunset</p>
					</div>
					<p class="text-2xl">{sunsetTime}</p>
				</div>
				<!-- Arc showing sun position -->
				<div class="relative w-full h-12">
					<svg viewBox="0 0 100 25" class="w-full h-full overflow-visible">
						<path d="M0,25 Q50,0 100,25" stroke="white" stroke-width="1" fill="none" />
						<circle cx={xSun} cy={ySun} r="3" fill="white" />
					</svg>
				</div>
				<p class="mt-2 text-lg">Sunrise: {sunriseTime}</p>
			</div>
		{:else if $displayMode === 'Large'}
			{#if sunTimesArray.length > 1}
				<div class="mt-1 w-full max-w-2xl">
					<div class="flex flex-col pb-4">
						<div class="text-left text-3xl font-semibold">{sunTimesArray[1].sunrise}</div>
						<div class="text-sm">Sunrise Tomorrow</div>
					</div>

					<div class="flex flex-row justify-between border-b border-gray-300 py-2">
						<div class="text-sm">First Light</div>
						<div class="text-right">
							{formatTimeFromMinutes(
								Math.max(parseTimeToMinutes(sunTimesArray[0].sunrise) - 30, 0)
							)}
						</div>
					</div>
					<div class="flex flex-row justify-between border-b border-gray-300 py-2">
						<div class="text-sm">Sunrise Today</div>
						<div class="text-right">{sunTimesArray[0].sunrise}</div>
					</div>
					<div class="flex flex-row justify-between border-b border-gray-300 py-2">
						<div class="text-sm">Sunset Today</div>
						<div class="text-right">{sunTimesArray[0].sunset}</div>
					</div>
					<div class="flex flex-row justify-between border-b border-gray-300 py-2">
						<div class="text-sm">Last Light</div>
						<div class="text-right">
							{formatTimeFromMinutes(
								Math.min(parseTimeToMinutes(sunTimesArray[0].sunset) + 30, 1440)
							)}
						</div>
					</div>
					<div class="flex flex-row justify-between border-b border-gray-300 py-2">
						<div class="text-sm">Total Daylight Duration</div>
						<div class="text-right">
							{formatDuration(
								parseTimeToMinutes(sunTimesArray[0].sunset) -
									parseTimeToMinutes(sunTimesArray[0].sunrise)
							)}
						</div>
					</div>
				</div>
			{/if}

			<p class="mt-4">Sunrise &amp; Sunset for the upcoming days</p>
			<div class="overflow-y-auto" style="max-height: 150px;">
				<div class="text-center px-2 flex flex-col items-center w-full">
					{#each sunTimesArray as sunData (sunData.date)}
						<div
							class="mx-2 border-b border-gray-300 p-1 my-1 grid grid-cols-[auto,auto,auto,auto] items-center gap-6 w-full max-w-2xl"
						>
							<!-- Weekday -->
							<p class="text-sm text-center w-4">
								{new Date(sunData.date).toLocaleDateString(undefined, { weekday: 'short' })}
							</p>
							<!-- Sunrise -->
							<p class="text-sm text-center w-8">{sunData.sunrise}</p>
							<!-- Horizontal Bar -->
							<div class="relative h-1 bg-gray-200 w-16 rounded-full">
								<div
									class="h-full bg-blue-200 absolute rounded-full"
									style="left: {(parseTimeToMinutes(sunData.sunrise) / 1440) *
										100}%; width: {((parseTimeToMinutes(sunData.sunset) -
										parseTimeToMinutes(sunData.sunrise)) /
										1440) *
										100}%"
								></div>
							</div>
							<!-- Sunset -->
							<p class="text-sm text-center w-8">{sunData.sunset}</p>
						</div>
					{/each}
				</div>
			</div>
		{/if}
	{/if}
</div>

<style>
	/* Add any additional styles as needed */
</style>
