// apps/website/src/pages/company/contact_us.tsx
import React, { useState } from "react";
import Head from "next/head";
import TextField from "@/components/ui/TextField";
import TextArea from "@/components/ui/TextArea";
import { Button } from "@graminate/ui";
import emailjs from "@emailjs/browser";
import Toast from "@/components/ui/Toast";
import { triggerToast } from "@/stores/toast";
import CurrentLocation from "@/components/others/CurrentLocation";
import DropdownSmall from "@/components/ui/Dropdown/DropdownSmall";
import { services } from "@/lib/constants";
import { ContactInfo, ContactErrors } from "@/lib/types";
import DefaultLayout from "@/layout/DefaultLayout";

const SERVICE_ID = process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID;
const TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID;
const PUBLIC_KEY = process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY;

export default function ContactUs() {
  const [contactInfo, setContactInfo] = useState<ContactInfo>({
    firstName: "",
    lastName: "",
    email: "",
    service: "",
    message: "",
  });

  const [errors, setErrors] = useState<ContactErrors>({
    firstName: "",
    lastName: "",
    email: "",
    service: "",
    message: "",
  });

  function validateForm(values: ContactInfo): boolean {
    let valid = true;
    const newErrors: ContactErrors = {
      firstName: "",
      lastName: "",
      email: "",
      service: "",
      message: "",
    };

    if (!values.firstName.trim()) {
      newErrors.firstName = "First name is required";
      valid = false;
    }

    if (!values.lastName.trim()) {
      newErrors.lastName = "Last name is required";
      valid = false;
    }

    if (!values.service) {
      newErrors.service = "Please select a service";
      valid = false;
    }

    if (
      !values.email.trim() ||
      !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)
    ) {
      newErrors.email = "Enter a valid email address";
      valid = false;
    }

    if (!values.message.trim()) {
      newErrors.message = "Enter a message";
      valid = false;
    }

    setErrors(newErrors);
    return valid;
  }

  async function handleSubmit(e?: React.FormEvent) {
    if (e) e.preventDefault();
    if (!validateForm(contactInfo)) return;

    try {
      await emailjs.send(
        SERVICE_ID!,
        TEMPLATE_ID!,
        {
          ...contactInfo,
          service: contactInfo.service || "Not specified",
        },
        PUBLIC_KEY
      );
      triggerToast(
        "Message sent successfully. A representative will be with you shortly."
      );
      setContactInfo({
        firstName: "",
        lastName: "",
        email: "",
        service: "",
        message: "",
      });
    } catch (error) {
      console.error("Error sending email:", error);
      triggerToast("Error sending message. Please try again later.");
    }
  }

  return (
    <>
      <Head>
        <title>Graminate | Contact Us</title>
      </Head>

      <DefaultLayout>
        <div className="team-cover">
          <div className="container mx-auto px-10 h-full">
            <div className="flex items-center h-full py-10">
              <div className="max-w-xl text-white">
                <p className="text-2xl md:text-2xl">
                  Need IT consultations or customized software solutions?
                </p>
                <br />
                <p className="text-xl text-gray-300 md:text-xl">
                  Contact our team and turn your ideas into reality.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="container mx-auto flex h-full flex-col p-6">
          <h2 className="text-center text-3xl font-bold lg:text-left">
            Get in Touch
          </h2>
          <div className="flex flex-col gap-8 lg:flex-row">
            {/* Contact Form */}
            <div className="w-full lg:w-1/2">
              <form onSubmit={handleSubmit} className="w-full px-6 py-8">
                <div className="mb-6 grid grid-cols-1 gap-6 md:grid-cols-2">
                  <TextField
                    label="First Name"
                    placeholder="First Name"
                    value={contactInfo.firstName}
                    onChange={(val: string) =>
                      setContactInfo({
                        ...contactInfo,
                        firstName: val,
                      })
                    }
                  />

                  <TextField
                    label="Last Name"
                    placeholder="Last Name"
                    value={contactInfo.lastName}
                    onChange={(val: string) =>
                      setContactInfo({ ...contactInfo, lastName: val })
                    }
                  />
                </div>

                <div className="mb-6">
                  <TextField
                    label="Email"
                    placeholder="Email Address"
                    value={contactInfo.email}
                    onChange={(val: string) =>
                      setContactInfo({ ...contactInfo, email: val })
                    }
                  />
                  {errors.email && (
                    <p className="text-sm text-red-500">{errors.email}</p>
                  )}
                </div>

                <div className="mb-6">
                  <DropdownSmall
                    label="Select Service"
                    items={services}
                    selected={contactInfo.service}
                    onSelect={(val: string) =>
                      setContactInfo({ ...contactInfo, service: val })
                    }
                    placeholder="Choose a service"
                  />
                  {errors.service && (
                    <p className="text-sm text-red-500">{errors.service}</p>
                  )}
                </div>

                <div className="mb-6">
                  <TextField
                    label="If not listed, specify request"
                    placeholder="Specify Service Request"
                    value={contactInfo.service}
                    onChange={(val: string) =>
                      setContactInfo({ ...contactInfo, service: val })
                    }
                  />
                </div>

                <div className="mb-6">
                  <TextArea
                    label="Message"
                    placeholder="Your Message"
                    value={contactInfo.message}
                    onChange={(val: string) =>
                      setContactInfo({ ...contactInfo, message: val })
                    }
                  />
                  {errors.message && (
                    <p className="text-sm text-red-500">{errors.message}</p>
                  )}
                </div>

                <div className="flex justify-center lg:justify-start">
                  <Button
                    label="Send"
                    variant="secondary"
                    onClick={handleSubmit}
                  />
                </div>
              </form>
            </div>

            {/* Google Map */}
            <div className="w-full lg:w-1/2">
              <CurrentLocation />
            </div>
          </div>
        </div>
      </DefaultLayout>

      <Toast />
    </>
  );
}

// src/routes/contact-us/+page.svelte
<script lang="ts">
	import HomeNavbar from '@layout/Navbars/HomeNavbar.svelte';
	import Footer from '@layout/Footer.svelte';
	import TextArea from '@ui/TextArea.svelte';
	import TextField from '@ui/TextField.svelte';
	import { writable } from 'svelte/store';
	import Button from '@ui/Button.svelte';
	import emailjs from 'emailjs-com';
	import Toast from '@ui/Toast.svelte';
	import { triggerToast } from '../../stores/toast';
	import GoogleMap from '@others/CurrentLocation.svelte';

	let contactInfo = writable<Record<string, string>>({
		firstName: '',
		lastName: '',
		email: '',
		message: ''
	});

	let errors = writable<Record<string, string>>({
		firstName: '',
		lastName: '',
		email: '',
		message: ''
	});

	const SERVICE_ID = import.meta.env.VITE_EMAILJS_SERVICE_ID;
	const TEMPLATE_ID = import.meta.env.VITE_EMAILJS_TEMPLATE_ID;
	const PUBLIC_KEY = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;

	function validateForm(values: Record<string, string>): boolean {
		let valid = true;
		let newErrors: Record<string, string> = {};

		if (!values.firstName.trim()) {
			newErrors.firstName = 'First name is required';
			valid = false;
		}

		if (!values.lastName.trim()) {
			newErrors.lastName = 'Last name is required';
			valid = false;
		}

		if (!values.email.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)) {
			newErrors.email = 'Valid email is required';
			valid = false;
		}

		if (!values.message.trim()) {
			newErrors.message = 'Message cannot be empty';
			valid = false;
		}

		errors.set(newErrors);
		return valid;
	}

	async function handleSubmit() {
		contactInfo.subscribe(async (values) => {
			if (!validateForm(values)) return;

			try {
				await emailjs.send(SERVICE_ID, TEMPLATE_ID, values, PUBLIC_KEY);
				triggerToast('Message sent successfully!');
				contactInfo.set({ firstName: '', lastName: '', email: '', message: '' });
			} catch (error) {
				console.error('Error sending email:', error);
				triggerToast('Failed to send message. Please try again.');
			}
		})();
	}
</script>

<svelte:head>
	<title>Contact Us</title>
</svelte:head>

<HomeNavbar signIn />

<div class="bg-gray-500">
	<div
		class="mx-auto max-w-7xl px-6 py-24 sm:py-24 lg:flex lg:items-center lg:justify-between lg:px-8"
	>
		<h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
			Would you like to cooperate with us?<br />We look forward to seeing you!
		</h2>
		<div class="mt-10 flex items-center gap-x-6 lg:mt-0 lg:flex-shrink-0">
			<a
				href="/"
				class="rounded-md bg-emerald-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600"
			>
				Set an Appointment
			</a>
		</div>
	</div>
</div>

<div class="p-6 flex flex-col h-full">
	<h2 class="text-3xl font-bold text-center lg:text-left">Get in Touch With Us</h2>
	<div class="flex flex-col lg:flex-row gap-8">
		<!-- Contact Form -->
		<div class="w-full lg:w-1/2">
			<form on:submit|preventDefault={handleSubmit} class="w-full px-6 py-8">
				<div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
					<TextField
						label="First Name"
						placeholder="Your First Name"
						type="text"
						bind:value={$contactInfo.firstName}
					/>
					<TextField
						label="Last Name"
						placeholder="Your Last Name"
						type="text"
						bind:value={$contactInfo.lastName}
					/>
				</div>

				<div class="mb-6">
					<TextField
						label="Email Address"
						placeholder="Enter your email"
						type="email"
						bind:value={$contactInfo.email}
					/>
					{#if $errors.email}<p class="text-red-500 text-sm">{$errors.email}</p>{/if}
				</div>

				<div class="mb-6">
					<TextArea
						label="Message"
						placeholder="Your message here"
						type="text"
						bind:value={$contactInfo.message}
					/>
					{#if $errors.message}<p class="text-red-500 text-sm">{$errors.message}</p>{/if}
				</div>

				<div class="flex justify-center lg:justify-start">
					<Button text="Send" style="primary" width="large" on:click={handleSubmit} />
				</div>
			</form>
		</div>

		<!-- Google Map -->
		<div class="w-full lg:w-1/2">
			<GoogleMap />
		</div>
	</div>
</div>

<Toast />
<Footer />
