// apps/frontend/src/components/layout/Sidebar.tsx
import React, { useState, useEffect, useMemo } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHome,
  faUsers,
  faAddressBook,
  faCloud,
  faDollar,
  faWarehouse,
  faChevronRight,
  faChevronLeft,
  faCow,
  faPlus,
  IconDefinition,
} from "@fortawesome/free-solid-svg-icons";

import type { Sidebar as SidebarProps } from "@/types/card-props";
import Loader from "../ui/Loader";
import { useUserPreferences } from "@/contexts/UserPreferencesContext";
import { getTranslator, TranslationKey } from "@/translations";
import BeeIcon from "@/icons/BeeIcon";
import PoultryIcon from "@/icons/PoultryIcon";

type SidebarSection = {
  icon: IconDefinition | React.ElementType;
  labelKey: TranslationKey;
  section: string;
  route?: string;
  basePath?: string;
  subItems: { labelKey: TranslationKey; route: string }[];
};

const Sidebar = ({ isOpen, userId, onSectionChange }: SidebarProps) => {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const {
    language: currentLanguage,
    userType,
    subTypes,
    isSubTypesLoading,
    fetchUserSubTypes,
  } = useUserPreferences();
  const t = useMemo(() => getTranslator(currentLanguage), [currentLanguage]);

  const [isCollapsed, setIsCollapsed] = useState(false);
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  useEffect(() => {
    if (userId) {
      fetchUserSubTypes(userId);
    }
  }, [userId, fetchUserSubTypes]);

  const sections: SidebarSection[] = useMemo(() => {
    const base: SidebarSection[] = [
      {
        icon: faHome,
        labelKey: "dashboard",
        section: "Dashboard",
        route: `/${userId}`,
        subItems: [],
      },
      {
        icon: faAddressBook,
        labelKey: "crm",
        section: "CRM",
        basePath: `/${userId}/crm`,
        subItems: [
          {
            labelKey: "contacts",
            route: `/${userId}/crm?view=contacts`,
          },
          {
            labelKey: "companies",
            route: `/${userId}/crm?view=companies`,
          },
          {
            labelKey: "contracts",
            route: `/${userId}/crm?view=contracts`,
          },
          {
            labelKey: "receipts",
            route: `/${userId}/crm?view=receipts`,
          },
          { labelKey: "projects", route: `/${userId}/crm?view=tasks` },
        ],
      },
    ];

    if (userType === "Producer") {
      if (subTypes.includes("Poultry")) {
        base.push({
          icon: PoultryIcon,
          labelKey: "poultryFarm",
          section: "Poultry Farm",
          route: `/${userId}/poultry`,
          subItems: [],
        });
      }
      if (subTypes.includes("Cattle Rearing")) {
        base.push({
          icon: faCow,
          labelKey: "cattleRearing",
          section: "Cattle Rearing",
          route: `/${userId}/cattle_rearing`,
          subItems: [],
        });
      }
      if (subTypes.includes("Apiculture")) {
        base.push({
          icon: BeeIcon,
          labelKey: "apiculture",
          section: "Apiculture",
          route: `/${userId}/apiculture`,
          subItems: [],
        });
      }
      base.push({
        icon: faCloud,
        labelKey: "weatherMonitor",
        section: "Weather Monitor",
        route: `/${userId}/weather`,
        subItems: [],
      });
    }

    base.push(
      {
        icon: faUsers,
        labelKey: "employees",
        section: "Labour",
        basePath: `/${userId}/labour`,
        subItems: [
          {
            labelKey: "database",
            route: `/${userId}/labour_database`,
          },
          {
            labelKey: "salaryManager",
            route: `/${userId}/labour_payment`,
          },
        ],
      },
      {
        icon: faDollar,
        labelKey: "finance",
        section: "Finance",
        route: `/${userId}/finance_dashboard`,
        subItems: [
          {
            labelKey: "dashboard",
            route: `/${userId}/finance_dashboard`,
          },
          {
            labelKey: "sales",
            route: `/${userId}/finance_sales`,
          },
          {
            labelKey: "expenses",
            route: `/${userId}/finance_expenses`,
          },
        ],
      },
      {
        icon: faWarehouse,
        labelKey: "storage",
        section: "storage",
        route: `/${userId}/storage`,
        subItems: [],
      },
      {
        icon: faPlus,
        labelKey: "addService",
        section: "Add Service",
        route: `/${userId}/add_service`,
        subItems: [],
      }
    );

    return base;
  }, [userId, userType, subTypes]);

  const navigateTo = (route: string) => {
    router.push(route);
    setExpandedSection(null);
  };

  const handleSectionToggle = (
    section: string,
    hasSubItems: boolean,
    route?: string
  ) => {
    if (route && !hasSubItems) {
      navigateTo(route);
    } else if (hasSubItems) {
      const isOpen = expandedSection === section;
      setExpandedSection(isOpen ? null : section);
      if (!isOpen && onSectionChange) onSectionChange(section);
    }
  };

  const toggleCollapse = () => {
    setIsCollapsed((c) => !c);
    setExpandedSection(null);
  };

  const closeSubMenu = () => setExpandedSection(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      const side = document.querySelector(".sidebar-container");
      if (side && !side.contains(e.target as Node)) closeSubMenu();
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  useEffect(() => {
    if (!isOpen) closeSubMenu();
  }, [isOpen]);

  return (
    <div
      className={`sidebar-container fixed inset-y-0 left-0 bg-gradient-to-b from-gray-800 to-gray-900 text-gray-300 shadow-xl transform transition-transform duration-300 ease-in-out z-50 flex flex-col ${
        isOpen ? "translate-x-0" : "-translate-x-full"
      } lg:translate-x-0 lg:relative lg:shadow-none`}
      style={{ width: isCollapsed ? 60 : 230 }}
    >
      <nav className="flex-1 overflow-y-auto py-4 space-y-1">
        {isSubTypesLoading ? (
          <div className="text-center text-gray-400 text-sm px-4">
            <Loader />
            {!isCollapsed && <p className="mt-2">{t("loadingSidebar")}</p>}
          </div>
        ) : (
          sections.map(
            ({ icon, labelKey, section, route, basePath, subItems }) => {
              const hasSubItems = subItems.length > 0;
              const translatedLabel = t(labelKey);
              const isActive =
                (!hasSubItems && pathname === route) ||
                (hasSubItems && basePath && pathname.startsWith(basePath)) ||
                expandedSection === section;

              return (
                <div key={section} className="relative px-3">
                  <div
                    className={`flex items-center p-3 rounded-lg cursor-pointer group transition-colors duration-200 ${
                      isActive
                        ? "bg-gray-700 text-white shadow-md"
                        : "text-gray-400 hover:bg-gray-700 hover:text-gray-300"
                    } ${isCollapsed ? "justify-center" : ""}`}
                    role="button"
                    tabIndex={0}
                    title={isCollapsed ? translatedLabel : ""}
                    onClick={() =>
                      handleSectionToggle(section, hasSubItems, route)
                    }
                    onKeyDown={(e) => {
                      if (e.key === "Enter" || e.key === " ") {
                        e.preventDefault();
                        handleSectionToggle(section, hasSubItems, route);
                      }
                    }}
                  >
                    {typeof icon === "object" && "prefix" in icon ? (
                      <FontAwesomeIcon
                        icon={icon}
                        className={`h-5 w-5 ${isCollapsed ? "" : "mr-3"}`}
                      />
                    ) : (
                      <div
                        className={`h-5 w-5 ${
                          isCollapsed ? "" : "mr-3"
                        } flex items-center justify-center text-current`}
                      >
                        {React.createElement(icon)}
                      </div>
                    )}

                    {!isCollapsed && (
                      <>
                        <span className="flex-grow font-medium text-sm truncate">
                          {translatedLabel}
                        </span>
                        {hasSubItems && (
                          <FontAwesomeIcon
                            icon={faChevronRight}
                            className={`h-3 w-3 transition-transform duration-200 ${
                              expandedSection === section ? "rotate-90" : ""
                            } ${
                              isActive
                                ? "text-white"
                                : "text-gray-500 group-hover:text-gray-300"
                            }`}
                          />
                        )}
                      </>
                    )}
                  </div>

                  {!isCollapsed &&
                    expandedSection === section &&
                    hasSubItems && (
                      <div className="mt-1 ml-5 pl-3 border-l border-gray-600 space-y-1">
                        {subItems.map((sub) => {
                          const translatedSubLabel = t(sub.labelKey);
                          const isSubActive =
                            pathname +
                              (searchParams.toString()
                                ? `?${searchParams.toString()}`
                                : "") ===
                            sub.route;
                          return (
                            <div
                              key={translatedSubLabel}
                              className={`text-sm py-2 px-4 rounded-md cursor-pointer transition-colors duration-150 ${
                                isSubActive
                                  ? "text-indigo-300 font-semibold"
                                  : "text-gray-400 hover:text-white hover:bg-gray-700"
                              }`}
                              role="button"
                              tabIndex={0}
                              onClick={() => navigateTo(sub.route)}
                              onKeyDown={(e) => {
                                if (e.key === "Enter" || e.key === " ") {
                                  e.preventDefault();
                                  navigateTo(sub.route);
                                }
                              }}
                            >
                              {translatedSubLabel}
                            </div>
                          );
                        })}
                      </div>
                    )}
                </div>
              );
            }
          )
        )}
      </nav>

      <div className="mt-auto p-3 border-t border-gray-700">
        <button
          className={`w-full flex items-center p-2 rounded-lg text-gray-400 hover:bg-gray-700 hover:text-gray-300 transition-colors duration-200 ${
            isCollapsed ? "justify-center" : "justify-end"
          }`}
          onClick={toggleCollapse}
          title={isCollapsed ? t("expandSidebar") : t("collapseSidebar")}
        >
          <FontAwesomeIcon
            icon={isCollapsed ? faChevronRight : faChevronLeft}
            className="h-5 w-5"
          />
        </button>
      </div>
    </div>
  );
};

export default Sidebar;

// src/components/layout/Sidebar.svelte
<script lang="ts">
	import { Fa } from 'svelte-fa';
	import {
		faHome,
		faChartPie,
		faChartLine,
		faUsers,
		faCartShopping,
		faAddressBook,
		faCloud,
		faPlug
	} from '@fortawesome/free-solid-svg-icons';
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';
	import { t } from '../../lib/i18n';
	import { locale } from 'svelte-i18n';

	export let isOpen: boolean;

	let isCollapsed = false;
	let expandedSection: string | null = null;

	const sections = [
		{
			icon: faHome,
			label: 'dashboard',
			section: 'Dashboard',
			route: '/platform',
			subItems: []
		},
		{
			icon: faAddressBook,
			label: 'crm',
			section: 'CRM',
			subItems: [
				{ label: 'contacts', route: '/platform/contacts' },
				{ label: 'companies', route: '/platform/contacts?view=companies' },
				{ label: 'deals', route: '/platform/contacts?view=deals' },
				{ label: 'Invoices', route: '/platform/contacts?view=invoices' },
				{ label: 'tickets', route: '/platform/contacts?view=tickets' }
			]
		},
		{
			icon: faChartPie,
			label: 'finder',
			section: 'Finder',
			route: '/platform/finder',
			subItems: []
		},
		{
			icon: faCartShopping,
			label: 'shop',
			section: 'Shop',
			subItems: []
		},
		{
			icon: faChartLine,
			label: 'commodity_prices',
			section: 'Commodity Prices',
			route: '/platform/commodity',
			subItems: []
		},
		{
			icon: faCloud,
			label: 'weather_monitor',
			section: 'Weather Monitor',
			route: '/platform/weather',
			subItems: []
		},
		{
			icon: faUsers,
			label: 'employees',
			section: 'Employees',
			subItems: [{ label: 'meetings', route: '/platform/meetings' }]
		},
		{
			icon: faPlug,
			label: 'apps_integration',
			section: 'Apps & Integration',
			route: '',
			subItems: []
		}
	];

	function navigateTo(route: string) {
		goto(route);
	}

	function handleSectionChange(section: string) {
		expandedSection = expandedSection === section ? null : section;
	}

	function toggleCollapse() {
		isCollapsed = !isCollapsed;
	}

	function closeSubMenu() {
		expandedSection = null;
	}

	onMount(() => {
		const handleClickOutside = (event: MouseEvent) => {
			const sidebar = document.querySelector('.sidebar');
			const navbar = document.querySelector('.navbar');

			if (
				(!sidebar || !sidebar.contains(event.target as Node)) &&
				(!navbar || !navbar.contains(event.target as Node))
			) {
				closeSubMenu();
			}
		};

		document.addEventListener('click', handleClickOutside);

		return () => {
			document.removeEventListener('click', handleClickOutside);
		};
	});
</script>

<div
	class="fixed py-3 inset-y-0 left-0 bg-gray-800 shadow-lg transform lg:translate-x-0 {isOpen
		? 'translate-x-0'
		: '-translate-x-full'} transition-transform duration-300 ease-in-out z-50 lg:relative lg:translate-x-0 sidebar"
	style="width: {isCollapsed ? '60px' : '230px'}"
>
	<nav class="space-y-2 flex flex-col relative">
		{#if $locale}
			{#each sections as { icon, label, section, route, subItems }}
				<div class="relative group">
					<div
						class="flex items-center mx-2 p-3 rounded-lg cursor-pointer hover:bg-blue-100 transition-all duration-200 group"
						role="button"
						tabindex="0"
						onclick={() => (route ? navigateTo(route) : handleSectionChange(section))}
						onkeydown={(e) => {
							if (e.key === 'Enter' || e.key === ' ') {
								route ? navigateTo(route) : handleSectionChange(section);
							}
						}}
						style="justify-content: {isCollapsed ? 'center' : 'flex-start'};"
					>
						<div class="text-gray-400 flex justify-center items-center w-6 h-6">
							<Fa {icon} />
						</div>
						{#if !isCollapsed}
							<span class="text-gray-500 font-light text-sm ml-2 flex-grow">{$t(label)}</span>
							{#if subItems.length > 0}
								<div
									class="ml-auto opacity-0 group-hover:opacity-100 transition-opacity duration-200"
								>
									<svg
										fill="#ffffff"
										height="12px"
										width="12px"
										version="1.1"
										id="Layer_1"
										xmlns="http://www.w3.org/2000/svg"
										xmlns:xlink="http://www.w3.org/1999/xlink"
										viewBox="0 0 330 330"
										xml:space="preserve"
									>
										<path
											id="XMLID_222_"
											d="M250.606,154.389l-150-149.996c-5.857-5.858-15.355-5.858-21.213,0.001
					c-5.857,5.858-5.857,15.355,0.001,21.213l139.393,139.39L79.393,304.394c-5.857,5.858-5.857,15.355,0.001,21.213
					C82.322,328.536,86.161,330,90,330s7.678-1.464,10.607-4.394l149.999-150.004c2.814-2.813,4.394-6.628,4.394-10.606
					C255,161.018,253.42,157.202,250.606,154.389z"
										/>
									</svg>
								</div>
							{/if}
						{/if}
					</div>

					{#if expandedSection === section && subItems.length > 0}
						<div
							class="absolute top-0 left-full bg-gray-800 shadow-lg rounded-md py-2 w-48 space-y-2"
							style="transform: translateX(10px);"
						>
							{#each subItems as { label, route }}
								<div
									class="text-gray-400 text-sm py-2 px-4 mx-2 cursor-pointer hover:bg-blue-100 rounded-md"
									role="button"
									tabindex="0"
									onclick={() => navigateTo(route)}
									onkeydown={(e) => {
										if (e.key === 'Enter' || e.key === ' ') {
											navigateTo(route);
										}
									}}
								>
									{$t(label)}
								</div>
							{/each}
						</div>
					{/if}
				</div>
			{/each}
		{:else}
			<p>Loading translations...</p>
		{/if}
	</nav>

	<div class="absolute bottom-4 right-4">
		<button
			class="flex items-center justify-center p-1 rounded-full bg-gray-400 text-gray-200 shadow-lg"
			onclick={toggleCollapse}
		>
			{#if isCollapsed}
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke-width="1.5"
					stroke="currentColor"
					class="size-4"
				>
					<path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
				</svg>
			{/if}
			{#if !isCollapsed}
				<svg
					xmlns="http://www.w3.org/2000/svg"
					fill="none"
					viewBox="0 0 24 24"
					stroke-width="1.5"
					stroke="currentColor"
					class="size-4"
				>
					<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
				</svg>
			{/if}
		</button>
	</div>
</div>
