// src/components/tables/Table.svelte
<script lang="ts">
	import Swal from 'sweetalert2';
	import { writable, derived, type Writable, type Readable } from 'svelte/store';
	import SearchBar from '@ui/SearchBar.svelte';
	import Button from '@ui/Button.svelte';
	import Dropdown from '@ui/Dropdown/DropdownLarge.svelte';

	export let onRowClick: (row: any[]) => void;

	export let data: { columns: string[]; rows: any[][] };
	export let filteredRows: Readable<any[][]>;
	export let currentPage: Writable<number>;
	export let itemsPerPage: Writable<number>;
	export let paginationItems: string[];
	export let searchQuery: Writable<string>;
	export let totalRecordCount: number;
	export let view: string = '';
	export let exportEnabled: boolean = true; // New parameter

	const sortOrder = writable<'asc' | 'desc'>('asc');
	const sortColumn = writable<number | null>(null);

	let selectAll: boolean = false;

	const selectedRows = writable<boolean[]>([]);

	const paginatedRows: Readable<any[][]> = derived(
		[filteredRows, currentPage, itemsPerPage],
		([$filteredRows, $currentPage, $itemsPerPage]) => {
			const start = ($currentPage - 1) * $itemsPerPage;
			const end = start + $itemsPerPage;
			return $filteredRows.slice(start, end);
		},
		[]
	);

	$: if ($paginatedRows.length > 0) {
		selectedRows.set(Array($paginatedRows.length).fill(selectAll));
	}

	const selectedRowCount = derived(
		selectedRows,
		($selectedRows) => $selectedRows.filter((isSelected) => isSelected).length
	);

	function exportTableData() {
		if ($sortedAndPaginatedRows.length === 0) {
			Swal.fire('No Data', 'There is no data to export.', 'info');
			return;
		}

		const csvContent = [
			data.columns.join(','), // Header row
			...$sortedAndPaginatedRows.map((row) => row.join(',')) // Data rows
		].join('\n');

		const blob = new Blob([csvContent], { type: 'text/csv' });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = `${view}.csv`; // Filename is the view name
		document.body.appendChild(a);
		a.click();
		document.body.removeChild(a);
		URL.revokeObjectURL(url);
	}

	function handleSelectAllChange() {
		selectedRows.update(() => Array($paginatedRows.length).fill(selectAll));
	}

	function handleRowCheckboxChange(rowIndex: number, event: Event) {
		const target = event.target as HTMLInputElement;
		if (target) {
			const isChecked = target.checked;
			selectedRows.update(($selectedRows) => {
				$selectedRows[rowIndex] = isChecked;
				selectAll = $selectedRows.every((checked) => checked);
				return $selectedRows;
			});
		}
	}

	async function deleteSelectedRows() {
		const rowsToDelete: number[] = [];

		selectedRows.subscribe(($selectedRows) => {
			$selectedRows.forEach((isSelected, index) => {
				if (isSelected) {
					const id = $paginatedRows[index][0];
					rowsToDelete.push(id);
				}
			});
		})();

		if (rowsToDelete.length === 0) {
			Swal.fire('No Selection', 'Please select at least one row to delete.', 'info');
			return;
		}

		const result = await Swal.fire({
			title: 'Are you sure?',
			text: `Do you want to delete ${view === 'companies' ? 'companies' : view === 'contacts' ? 'contacts' : 'deals'}?`,
			icon: 'warning',
			showCancelButton: true,
			confirmButtonText: 'Yes',
			cancelButtonText: 'No',
			reverseButtons: true
		});

		if (result.isConfirmed) {
			try {
				const endpoint = view === 'companies' ? 'companies' : view === 'contacts' ? 'contacts' : 'deals';

				await Promise.all(
					rowsToDelete.map(async (id) => {
						const response = await fetch(`http://localhost:3000/api/${endpoint}/delete/${id}`, {
							method: 'DELETE'
						});

						if (!response.ok) {
							throw new Error(`Failed to delete ${endpoint.slice(0, -1)} with id ${id}`);
						}
					})
				);

				location.reload();
			} catch (error) {
				console.error('Error deleting rows:', error);
				Swal.fire('Error', 'Failed to delete selected rows. Please try again.', 'error');
			}
		}
	}

	function toggleSort(columnIndex: number) {
		if (columnIndex === $sortColumn) {
			sortOrder.set($sortOrder === 'asc' ? 'desc' : 'asc');
		} else {
			sortColumn.set(columnIndex);
			sortOrder.set('asc');
		}

		currentPage.set(1);
	}

	function handleSelect(event: CustomEvent<{ item: string }>) {
		const selected = event.detail.item;

		if (selected === '25 per page') itemsPerPage.set(25);
		else if (selected === '50 per page') itemsPerPage.set(50);
		else if (selected === '100 per page') itemsPerPage.set(100);
	}

	const sortedAndPaginatedRows: Readable<any[][]> = derived(
		[paginatedRows, sortColumn, sortOrder],
		([$paginatedRows, $sortColumn, $sortOrder]) => {
			let rows = [...$paginatedRows];

			if ($sortColumn !== null) {
				rows.sort((a, b) => {
					const valueA = a[$sortColumn];
					const valueB = b[$sortColumn];

					if (typeof valueA === 'string' && typeof valueB === 'string') {
						return $sortOrder === 'asc'
							? valueA.localeCompare(valueB)
							: valueB.localeCompare(valueA);
					}
					if (typeof valueA === 'number' && typeof valueB === 'number') {
						return $sortOrder === 'asc' ? valueA - valueB : valueB - valueA;
					}
					return 0;
				});
			}

			return rows;
		},
		[]
	);
</script>

<div>
	<div
		class="flex p-1 justify-between items-center border-t border-l border-r border-gray-300 dark:border-gray-200"
	>
		<div class="flex gap-2">
			<SearchBar mode="table" placeholder="Search anything" bind:query={$searchQuery} />

			{#if $selectedRowCount > 0}
				<div class="flex items-center ml-4">
					<span class="text-gray-200 dark:text-gray-400 text-sm font-medium">
						{$selectedRowCount} selected
					</span>
					<button
						class="ml-2 text-blue-200 text-sm hover:underline cursor-pointer"
						onclick={(event) => {
							event.preventDefault();
							deleteSelectedRows();
						}}
					>
						Delete
					</button>
				</div>
			{/if}
		</div>

		<div class="flex gap-2">
			{#if exportEnabled}
				<Button style="secondary" text="Export Data" on:click={exportTableData} />
			{/if}
		</div>
	</div>

	{#if $sortedAndPaginatedRows.length > 0}
		<table class="table-auto w-full border">
			<thead>
				<tr>
					<th
						class="p-2 border border-gray-300 dark:border-gray-200 bg-gray-400 dark:bg-gray-800 text-left"
					>
						<input
							type="checkbox"
							class="form-checkbox h-4 w-4 text-gray-600"
							bind:checked={selectAll}
							onchange={handleSelectAllChange}
						/>
					</th>
					{#each data.columns as column, index}
						<th
							class="p-2 border border-gray-300 dark:border-gray-200 bg-gray-400 dark:bg-gray-800 dark:text-gray-500 cursor-pointer text-left"
							onclick={() => toggleSort(index)}
						>
							<div class="flex items-center justify-between">
								<span class="mr-2 font-semibold">{column}</span>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									stroke-width="1.5"
									stroke="currentColor"
									class="size-6"
								>
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										d="M8.25 15 12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9"
									/>
								</svg>
							</div>
						</th>
					{/each}
				</tr>
			</thead>

			<tbody>
				{#each $sortedAndPaginatedRows as row, rowIndex}
					<tr
						class="cursor-pointer hover:bg-gray-500 dark:hover:bg-gray-700"
						onclick={(event) => {
							if (!(event.target instanceof HTMLInputElement)) {
								onRowClick(row);
							}
						}}
					>
						<td class="p-2 border border-gray-300 dark:border-gray-200">
							<input
								type="checkbox"
								class="form-checkbox h-4 w-4 text-gray-200 dark:text-light"
								bind:checked={$selectedRows[rowIndex]}
								onchange={(event) => handleRowCheckboxChange(rowIndex, event)}
							/>
						</td>
						<!-- For deleting data from the table, there is a hidden column of ID. ID is required for removing data -->
						{#if view === 'contacts' || view === 'companies' || view === 'deals'}
							{#each row.slice(1) as cell}
								<td
									class="p-2 border border-gray-300 dark:border-gray-200 text-base font-light dark:text-gray-400"
								>
									{cell}
								</td>
							{/each}
						{:else}
							{#each row as cell}
								<td
									class="p-2 border border-gray-300 dark:border-gray-200 text-base font-light dark:text-gray-400"
								>
									{cell}
								</td>
							{/each}
						{/if}
					</tr>
				{/each}
			</tbody>
		</table>
	{:else}
		<div class="text-center p-4 text-gray-300">
			<span class="text-lg">⚠️</span> Record(s) not Found
		</div>
	{/if}

	<nav class="flex items-center justify-between px-4 py-3 sm:px-6" aria-label="Pagination">
		<div class="flex mx-auto px-5 items-center">
			<Button
				text="Previous"
				style="ghost"
				arrow="left"
				isDisabled={$currentPage === 1}
				on:click={() => $currentPage > 1 && currentPage.set($currentPage - 1)}
			/>

			<p class="mx-3 text-sm dark:text-light text-dark">
				<span class=" px-2 py-1 border border-gray-300 rounded-sm">{$currentPage} </span>
			</p>

			<Button
				text="Next"
				style="ghost"
				arrow="right"
				isDisabled={$currentPage === Math.ceil(totalRecordCount / $itemsPerPage)}
				on:click={() =>
					$currentPage < Math.ceil(totalRecordCount / $itemsPerPage) &&
					currentPage.set($currentPage + 1)}
			/>
		</div>
		<div class="relative">
			<Dropdown items={paginationItems} selectedItem="25 per page" on:select={handleSelect} />
		</div>
	</nav>
</div>

// packages/ui/lib/components/table/table.tsx
import React, { useState, useMemo, useRef, useEffect } from "react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Swal from "sweetalert2";

import { Dropdown } from "../dropdown/dropdown";
import { Icon } from "../icon/icon";
import { Checkbox } from "../checkbox/checkbox";
import { Button } from "../button/button";
import { SearchBar } from "../searchbar/searchbar";
import { TableSkeleton } from "./table-skeleton";

type RowType = unknown[];

type TableData = {
  columns: string[];
  rows: RowType[];
};

type Props = {
  onRowClick?: (row: RowType) => void;
  data: TableData;
  filteredRows: RowType[];
  currentPage: number;
  setCurrentPage: (page: number) => void;
  itemsPerPage: number;
  setItemsPerPage: (n: number) => void;
  paginationItems: string[];
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  totalRecordCount: number;
  view?: string;
  exportEnabled?: boolean;
  loading?: boolean;
  reset?: boolean;
  hideChecks?: boolean;
  download?: boolean;
  onDeleteRows?: (selectedRows: RowType[]) => Promise<void>;
  onResetTable?: () => Promise<void>;
};

const Table = ({
  onRowClick,
  data,
  filteredRows,
  currentPage,
  setCurrentPage,
  setItemsPerPage,
  paginationItems,
  searchQuery,
  setSearchQuery,
  totalRecordCount,
  view = "",
  loading,
  reset = true,
  hideChecks = false,
  download = true,
  onDeleteRows,
  onResetTable,
}: Props) => {
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");
  const [sortColumn, setSortColumn] = useState<number | null>(null);
  const [selectAll, setSelectAll] = useState(false);
  const [selectedRows, setSelectedRows] = useState<boolean[]>([]);
  const [showExportDropdown, setShowExportDropdown] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const [itemsPerPage, setItemsPerPageState] = useState(10);

  const effectiveLoading = loading;

  const paginatedRows = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    const end = start + itemsPerPage;
    return filteredRows.slice(start, end);
  }, [filteredRows, currentPage, itemsPerPage]);

  useEffect(() => {
    setSelectedRows(new Array(paginatedRows.length).fill(false));
    setSelectAll(false);
  }, [paginatedRows]);

  const selectedRowCount = selectedRows.filter(Boolean).length;

  const sortedAndPaginatedRows = useMemo(() => {
    const rows = [...paginatedRows];
    if (sortColumn !== null) {
      rows.sort((a: any, b: any) => {
        const valueA = a[sortColumn];
        const valueB = b[sortColumn];

        if (typeof valueA === "string" && typeof valueB === "string") {
          return sortOrder === "asc"
            ? valueA.localeCompare(valueB)
            : valueB.localeCompare(valueA);
        }
        if (typeof valueA === "number" && typeof valueB === "number") {
          return sortOrder === "asc" ? valueA - valueB : valueB - valueA;
        }
        return 0;
      });
    }
    return rows;
  }, [paginatedRows, sortColumn, sortOrder]);

  const getExportRows = () => {
    const selected = selectedRows
      .map((isSelected, idx) =>
        isSelected ? sortedAndPaginatedRows[idx] : null
      )
      .filter((row): row is RowType => row !== null);

    return selected.length > 0 ? selected : sortedAndPaginatedRows;
  };

  const exportTableData = (format: "pdf" | "xlsx") => {
    const exportRows = getExportRows();

    if (exportRows.length === 0) {
      Swal.fire("No Data", "There is no data to export.", "info");
      return;
    }

    if (format === "pdf") {
      const doc = new jsPDF();
      const filteredColumns = data.columns.filter((col) => col !== "#");
      const pdfBodyData = exportRows.map((row) =>
        (row as any[]).filter((_, idx) => data.columns[idx] !== "#").map((cell) => {
          if (cell === null || cell === undefined) return "";
          return String(cell);
        })
      );
      autoTable(doc, {
        head: [filteredColumns],
        body: pdfBodyData,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [52, 73, 94] },
      });
      doc.save(`${view}.pdf`);
    }

    if (format === "xlsx") {
      const filteredColumns = data.columns.filter((col) => col !== "#");
      const filteredExportRows = exportRows.map((row) =>
        (row as any[]).filter((_, idx) => data.columns[idx] !== "#")
      );
      const worksheet = XLSX.utils.aoa_to_sheet([filteredColumns, ...filteredExportRows]);
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");
      const wbout = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
      const blob = new Blob([wbout], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${view}.xlsx`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  };

  const handleSelectAllChange = (checked: boolean) => {
    setSelectAll(checked);
    setSelectedRows(new Array(paginatedRows.length).fill(checked));
  };

  const handleRowCheckboxChange = (
    rowIndex: number,
    checked: boolean
  ) => {
    setSelectedRows((prev) => {
      const newSelected = [...prev];
      newSelected[rowIndex] = checked;
      setSelectAll(newSelected.every(Boolean));
      return newSelected;
    });
  };

  const handleDeleteSelected = async () => {
    if (!onDeleteRows) return;
    
    const selectedRowsData = sortedAndPaginatedRows.filter((_, idx) => selectedRows[idx]);
    
    if (selectedRowsData.length === 0) {
      await Swal.fire(
        "No Selection",
        "Please select at least one row to delete.",
        "info"
      );
      return;
    }

    await onDeleteRows(selectedRowsData);
  };

  const toggleSort = (columnIndex: number) => {
    if (sortColumn === columnIndex) {
      setSortOrder((prev) => (prev === "asc" ? "desc" : "asc"));
    } else {
      setSortColumn(columnIndex);
      setSortOrder("asc");
    }
    setCurrentPage(1);
  };

  const handleSelect = (item: string) => {
    const itemsPerPageMap: Record<string, number> = {
      "10 per page": 10,
      "25 per page": 25,
      "50 per page": 50,
      "100 per page": 100,
    };
    const newItemsPerPage = itemsPerPageMap[item] || 10;
    setItemsPerPageState(newItemsPerPage);
    setItemsPerPage(newItemsPerPage);
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)] overflow-hidden transition-all">
      <div className="px-6 py-5 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-white dark:bg-gray-800">
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-4 w-full sm:w-auto">
          <div className="w-full max-w-[280px]">
            <SearchBar
              mode="table"
              placeholder="Search data..."
              value={searchQuery}
              onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                setSearchQuery(e.target.value)
              }
            />
          </div>
          {selectedRowCount > 0 && (
            <div className="flex items-center gap-3 px-4 py-2 animate-in fade-in slide-in-from-left-2 duration-300 flex-shrink-0">
              <span className="text-primary-700 dark:text-primary-300 whitespace-nowrap leading-none">
                {selectedRowCount} Selected
              </span>
              <div className="w-px h-3 bg-primary-200 dark:bg-primary-800 flex-shrink-0" />
              <button
                className="text-red-200 dark:text-red-400 hover:text-red-300 hover:cursor-pointer dark:hover:text-red-300 transition-colors whitespace-nowrap leading-none"
                onClick={(event) => {
                  event.preventDefault();
                  handleDeleteSelected();
                }}
              >
                Delete
              </button>
            </div>
          )}
        </div>
        <div className="flex flex-row items-center gap-2">
          {reset && onResetTable && (
            <Button
              variant="secondary"
              size="sm"
              label="Reset"
              disabled={filteredRows.length === 0}
              onClick={onResetTable}
            />
          )}

          {download && (
            <div className="relative" ref={dropdownRef}>
              <Button
                variant="secondary"
                size="sm"
                label="Download"
                icon={{ right: "download" }}
                disabled={filteredRows.length === 0}
                onClick={() => setShowExportDropdown(!showExportDropdown)}
              />
              {showExportDropdown && (
                <div className="absolute right-0 top-full mt-2 w-48 bg-white dark:bg-gray-700 border dark:border-gray-200 rounded-xl shadow-xl z-50 animate-in fade-in zoom-in-95 duration-200 overflow-hidden">
                  <button
                    className="w-full text-left text-sm px-4 py-3 hover:bg-neutral-50 dark:hover:bg-neutral-800/50 flex items-center gap-2 font-medium text-neutral-700 dark:text-neutral-300 transition-colors"
                    onClick={() => {
                      exportTableData("pdf");
                      setShowExportDropdown(false);
                    }}
                  >
                    <Icon type="picture_as_pdf" size={18} />
                    Export as PDF
                  </button>
                  <button
                    className="w-full text-left text-sm px-4 py-3 hover:bg-neutral-50 dark:hover:bg-neutral-800/50 flex items-center gap-2 font-medium text-neutral-700 dark:text-neutral-300 border-t border-gray-400 dark:border-gray-600 transition-colors"
                    onClick={() => {
                      exportTableData("xlsx");
                      setShowExportDropdown(false);
                    }}
                  >
                    <Icon type="table_chart" size={18} />
                    Export as Excel
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {effectiveLoading ? (
        <TableSkeleton
          columns={data.columns}
          rowCount={itemsPerPage}
          hideChecks={hideChecks}
        />
      ) : sortedAndPaginatedRows.length > 0 ? (
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-neutral-200 dark:divide-gray-700 bg-white dark:bg-gray-800">
            <thead className="text-xs text-gray-700 uppercase bg-gray-500 dark:bg-gray-700 dark:text-gray-400">
              <tr>
                {!hideChecks && (
                  <th
                    className="px-6 py-3 text-left"
                    onClick={(e) => e.stopPropagation()}
                  >
                    <Checkbox
                      id="select-all-checkbox"
                      checked={selectAll && paginatedRows.length > 0}
                      onCheckedChange={handleSelectAllChange}
                      disabled={paginatedRows.length === 0}
                      className="size-4"
                      aria-label={selectAll ? "Deselect all" : "Select all"}
                    />
                  </th>
                )}
                {data.columns.map((column, index) => column !== "#" && (
                  <th
                    key={index}
                    className="px-6 py-3 text-left text-xs font-bold text-neutral-500 dark:text-neutral-400 cursor-pointer group transition-colors duration-200 hover:bg-neutral-100 dark:hover:bg-neutral-800"
                    onClick={() => toggleSort(index)}
                  >
                    <div className="flex items-center gap-1.5 justify-start">
                      <span>{column}</span>
                      <Icon 
                        type={sortColumn === index ? (sortOrder === "asc" ? "arrow_drop_up" : "arrow_drop_down") : "unfold_more"} 
                        size={14} 
                        className={`transition-opacity duration-200 ${sortColumn === index ? "opacity-100 text-primary-500" : "opacity-0 group-hover:opacity-40"}`}
                      />
                    </div>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="bg-white dark:bg-gray-800">
              {sortedAndPaginatedRows.map((row, rowIndex) => (
                <tr
                  key={`row-${rowIndex}-${(row as any[])[0]}`}
                  className={`group cursor-pointer transition-all duration-200 ${
                    selectedRows[rowIndex]
                      ? "bg-primary-50/40 dark:bg-primary-900/10"
                      : "hover:bg-gray-50 dark:hover:bg-gray-600"
                  } border-b border-neutral-200 dark:border-gray-700`}
                  onClick={(e) => {
                    if (
                      (e.target as HTMLElement).tagName !== "INPUT" &&
                      (e.target as HTMLElement).closest("button") === null
                    ) {
                      onRowClick?.(row);
                    }
                  }}
                >
                  {!hideChecks && (
                    <td
                      className="px-6 py-4 whitespace-nowrap"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <Checkbox
                        id={`row-checkbox-${rowIndex}`}
                        checked={selectedRows[rowIndex] || false}
                        onCheckedChange={(checked: boolean) => handleRowCheckboxChange(rowIndex, !!checked)}
                        className="size-4 transition-transform group-hover:scale-105"
                        aria-label={`Select row ${rowIndex + 1}`}
                      />
                    </td>
                  )}

                  {(row as any[]).map((cell, cellIndex) => data.columns[cellIndex] !== "#" && (
                    <td
                      key={cellIndex}
                      className="px-6 py-4 whitespace-nowrap text-sm font-medium text-dark dark:text-light max-w-[240px] truncate"
                      title={
                        Array.isArray(cell)
                          ? cell.join(", ")
                          : typeof cell === "string" || typeof cell === "number"
                          ? String(cell)
                          : undefined
                      }
                    >
                      {view === "inventory" &&
                      data.columns[cellIndex] === "Status" ? (
                        <div className="flex gap-[2px] text-sm">
                          {(() => {
                            const quantityIndex =
                              data.columns.indexOf("Quantity");
                            if (quantityIndex === -1) return "?";
                            const quantityValue = (row as any[])[quantityIndex];
                            if (typeof quantityValue !== "number")
                              return (
                                <Icon
                                  type={"circle"}
                                  className="text-red-200"
                                />
                              );
                            const quantity = quantityValue;
                            const max = Math.max(
                              0,
                              ...filteredRows
                                .map((r) => (r as any[])[quantityIndex])
                                .filter(
                                  (q): q is number => typeof q === "number"
                                )
                            );
                            const ratio = max > 0 ? quantity / max : 0;
                            let count = 0;
                            let color = "";
                            if (quantity <= 0 || (max > 0 && ratio < 0.25)) {
                              count = 1;
                              color = "text-red-200";
                            } else if (max > 0 && ratio < 0.5) {
                              count = 2;
                              color = "text-orange-400";
                            } else if (max > 0 && ratio < 0.75) {
                              count = 3;
                              color = "text-yellow-200";
                            } else {
                              count = 4;
                              color = "text-green-200";
                            }
                            return Array.from({ length: count }).map((_, i) => (
                              <Icon
                                key={i}
                                type={"circle"}
                                className={color}
                              />
                            ));
                          })()}
                        </div>
                      ) : typeof cell === "string" ||
                        typeof cell === "number" ||
                        typeof cell === "boolean" ||
                        cell === null ||
                        cell === undefined ? (
                        String(cell)
                      ) : (
                        String(cell)
                      )}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div className="flex flex-col items-center justify-center py-20 px-6 text-center animate-in fade-in zoom-in-95 duration-500">
          <div className="size-16 rounded-2xl bg-neutral-50 dark:bg-neutral-800/50 flex items-center justify-center mb-4 border border-neutral-100 dark:border-neutral-800">
            <Icon type="search_off" size={32} className="text-neutral-400 dark:text-neutral-600" />
          </div>
          <h3 className="text-lg font-semibold text-neutral-900 dark:text-neutral-100 mb-1">No results found</h3>
          <p className="text-sm text-neutral-500 dark:text-neutral-400 max-w-xs">
            We couldn't find what you're looking for. Try adjusting your search or filters.
          </p>
        </div>
      )}

      {!effectiveLoading && totalRecordCount > 0 && (
        <nav
          className="flex flex-col sm:flex-row items-center justify-between px-6 py-5 bg-neutral-50/50 dark:bg-neutral-800/30 gap-4"
          aria-label="Pagination"
        >
          <div className="flex items-center gap-6 order-2 sm:order-1">
            <p className="text-[13px] text-neutral-500 dark:text-neutral-400 font-medium whitespace-nowrap">
              Showing <span className="text-neutral-900 dark:text-neutral-100">{Math.min((currentPage - 1) * itemsPerPage + 1, totalRecordCount)}</span> to <span className="text-neutral-900 dark:text-neutral-100">{Math.min(currentPage * itemsPerPage, totalRecordCount)}</span> of <span className="text-neutral-900 dark:text-neutral-100">{totalRecordCount}</span>
            </p>
            <div className="h-4 w-px bg-neutral-200 dark:bg-neutral-800 hidden sm:block" />
            <div className="relative z-[60]">
              <Dropdown
                direction="up"
                items={paginationItems}
                selectedItem={`${itemsPerPage} per page`}
                onSelect={handleSelect}
              />
            </div>
          </div>
          
          <div className="flex items-center gap-2 order-1 sm:order-2">
            <Button
              label="Prev"
              variant="ghost"
              size="sm"
              icon={{ left: "chevron_left" }}
              disabled={currentPage === 1}
              onClick={() => {
                if (currentPage > 1) setCurrentPage(currentPage - 1);
              }}
            />
            <div className="flex items-center rounded-lg px-3 py-1.5 shadow-sm">
              <span className="text-[13px] text-primary-600 dark:text-primary-400">{currentPage}</span>
              <span className="mx-1.5 text-neutral-300 dark:text-neutral-700">/</span>
              <span className="text-[13px] text-neutral-500 dark:text-neutral-500">{Math.ceil(totalRecordCount / itemsPerPage) || 1}</span>
            </div>
            <Button
              label="Next"
              variant="ghost"
              size="sm"
              icon={{ right: "chevron_right" }}
              disabled={
                currentPage === Math.ceil(totalRecordCount / itemsPerPage) ||
                totalRecordCount === 0
              }
              onClick={() => {
                if (currentPage < Math.ceil(totalRecordCount / itemsPerPage))
                  setCurrentPage(currentPage + 1);
              }}
            />
          </div>
        </nav>
      )}
    </div>
  );
};

export { Table };
export type { TableData };
