// src/components/ui/TextArea.svelte
<script>
	export let label = '';
	export let isDisabled = false;
	export let type = '';
	export let placeholder;
	export let value = '';

	let fieldClass = '';

	const getFieldClass = () => {
		switch (type) {
			case 'disabled':
				return 'border border-gray-400 opacity-50 text-gray-100 placeholder-gray-300 text-sm rounded-md block w-full p-2.5 focus:outline-none focus:ring-1 focus:ring-red-200';
			default:
				return 'border border-gray-400 dark:border-gray-200 text-dark dark:text-light placeholder-gray-300 text-sm rounded-md block w-full p-2.5 focus:outline-none focus:ring-1 focus:ring-green-200 dark:bg-gray-700';
		}
	};

	$: fieldClass = `${getFieldClass()} py-2 px-4 rounded`;
</script>

<div class="w-full">
	<label for="textarea" class="block mb-1 text-sm font-medium text-gray-200 dark:text-gray-300">
		{label}
	</label>
	<div class="relative flex items-start">
		<textarea
			class={fieldClass}
			disabled={isDisabled}
			{placeholder}
			id="textarea"
			rows="3"
			bind:value
		></textarea>
	</div>
</div>

// packages/ui/lib/components/textarea/textarea.tsx
import * as React from "react";
import { forwardRef } from "react";
import { cn } from "../../utils";
import { Layout } from "../layouts/layout";

type TextareaProps = React.ComponentPropsWithoutRef<"textarea"> & {
  id: string;
  label: string;
  hideLabel?: boolean;
  hint?: string;
  error?: string;
};

const TextArea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    { className, id, label, hideLabel, hint, error, placeholder, ...props },
    ref
  ) => {
    return (
      <Layout className="disabled:cursor-not-allowed disabled:opacity-50">
        <label className="flex flex-col gap-1.5 group/input disabled:pointer-events-none">
          <span
            className={
              hideLabel
                ? "sr-only"
                : "text-dark dark:text-light font-medium text-sm group-focus-within/input:text-neutral-dark-gray"
            }
          >
            {label}
          </span>

          <div
            className={cn(
              "flex flex-row gap-2 items-start py-2 px-3 rounded-[var(--radius-md)] border-1 border-neutral-light-gray/40 shadow-xs shadow-black/20 transition-colors",
              error && "border-red-200",
              "group-focus-within/input:!ring-1 group-focus-within/input:!ring-offset-2",
              error
                ? "group-focus-within/input:!ring-red-200"
                : "group-focus-within/input:!ring-green-200",
              className
            )}
          >
            <textarea
              className="border-none text-dark dark:text-light px-0.5 w-full placeholder-gray-300 focus:outline-none focus:placeholder-gray-300 text-sm min-h-16 field-sizing-content"
              id={id}
              name={id}
              ref={ref}
              placeholder={placeholder}
              {...props}
            />
          </div>
          {hint && (
            <span className="text-dark dark:text-light font-normal text-xs">
              {hint}
            </span>
          )}
          {error && <span className="text-red-400 text-xs">{error}</span>}
        </label>
      </Layout>
    );
  }
);

export { TextArea };
