// src/components/ui/Dropdown/DropdownFilter.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { onMount, onDestroy } from 'svelte';

	export let items: string[] = [];
	export let direction: 'up' | 'down' = 'down';
	export let placeholder: string = 'Select';
	export let selectedItems: string[] = [];

	const dispatch = createEventDispatcher();
	let isOpen = false;
	let dropdownRef: HTMLDivElement | null = null;

	function toggleDropdown() {
		isOpen = !isOpen;
	}

	function isItemSelected(item: string): boolean {
		return selectedItems.includes(item);
	}

	function toggleItem(item: string) {
		if (isItemSelected(item)) {
			selectedItems = selectedItems.filter((selectedItem) => selectedItem !== item);
		} else {
			selectedItems = [...selectedItems, item];
		}
		dispatch('change', selectedItems);
	}

	function handleClickOutside(event: MouseEvent) {
		if (dropdownRef && !dropdownRef.contains(event.target as Node)) {
			isOpen = false;
		}
	}

	onMount(() => {
		if (typeof document !== 'undefined') {
			document.addEventListener('click', handleClickOutside);
		}
	});

	onDestroy(() => {
		if (typeof document !== 'undefined') {
			document.removeEventListener('click', handleClickOutside);
		}
	});
</script>

<div class="relative inline-block text-left w-auto" bind:this={dropdownRef}>
	<button
		class="w-full hover:bg-gray-400 dark:hover:bg-gray-700 dark:text-gray-400 dark:focus:bg-green-950 focus:bg-green-400 focus:text-green-100 text-sm font-semibold px-3 py-2 rounded-md text-left flex items-center justify-between"
		on:click={toggleDropdown}
	>
		<span>
			{#if selectedItems.length > 0}
				{placeholder}
				<span class="bg-green-200 text-white mr-2 px-2 py-0.5 text-xs rounded-full"
					>{selectedItems.length}</span
				>
			{:else}
				{placeholder}
			{/if}
		</span>
		<svg
			xmlns="http://www.w3.org/2000/svg"
			fill="none"
			viewBox="0 0 24 24"
			stroke-width="1.5"
			stroke="currentColor"
			class="w-5 h-5"
		>
			<path stroke-linecap="round" stroke-linejoin="round" d="M6 9l6 6 6-6" />
		</svg>
	</button>

	{#if isOpen}
		<div
			class={`absolute z-10 w-auto mx-4 bg-white dark:bg-gray-700 rounded-md shadow-lg mt-2 ${
				direction === 'up' ? 'bottom-full mb-2' : ''
			}`}
		>
			{#each items as item}
				<label
					class="flex items-center px-4 py-2 cursor-pointer dark:hover:bg-blue-100 hover:bg-gray-400"
				>
					<input
						type="checkbox"
						class="form-checkbox text-blue-600 h-4 w-4 rounded border-gray-300 focus:ring-blue-500"
						checked={isItemSelected(item)}
						on:click={() => toggleItem(item)}
					/>
					<span class="ml-2 text-sm text-dark dark:text-light">{item}</span>
				</label>
			{/each}
		</div>
	{/if}
</div>

// apps/frontend/src/components/ui/Dropdown/DropdownFilter.tsx
import { Icon } from "@graminate/ui";
import React, { useState, useRef, useEffect } from "react";
import type { DropdownFilter } from "@/types/card-props";
import { Checkbox } from "@graminate/ui";

const DropdownFilter = ({
  items,
  direction = "down",
  placeholder = "Select",
  selectedItems,
  onChange,
}: DropdownFilter) => {
  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement | null>(null);

  const toggleDropdown = () => {
    setIsOpen(!isOpen);
  };

  const isItemSelected = (item: string): boolean =>
    selectedItems.includes(item);

  const toggleItem = (item: string) => {
    if (isItemSelected(item)) {
      onChange(selectedItems.filter((selectedItem) => selectedItem !== item));
    } else {
      onChange([...selectedItems, item]);
    }
  };

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setIsOpen(false);
      }
    };

    document.addEventListener("click", handleClickOutside);
    return () => {
      document.removeEventListener("click", handleClickOutside);
    };
  }, []);

  return (
    <div className="relative inline-block text-left w-auto" ref={dropdownRef}>
      {/* Toggle Button */}
      <button
        className="w-full hover:bg-gray-400 dark:hover:bg-gray-700 dark:text-gray-400 
        dark:focus:bg-gray-700 focus:bg-gray-400 focus:text-dark text-sm 
        px-3 py-2 rounded-md text-left flex items-center justify-between"
        onClick={toggleDropdown}
      >
        <span>
          {selectedItems.length > 0 ? (
            <>
              {placeholder}
              <span className="bg-green-200 text-white mr-2 px-2 py-0.5 text-xs rounded-full">
                {selectedItems.length}
              </span>
            </>
          ) : (
            placeholder
          )}
        </span>
        {/* Dropdown Icon */}
        <Icon type={"expand_more"} className="size-5" />
      </button>

      {/* Dropdown Menu */}
      {isOpen && (
        <div
          className={`absolute z-10 w-auto mx-4 bg-white dark:bg-gray-700 rounded-md shadow-lg mt-2 ${
            direction === "up" ? "bottom-full mb-2" : ""
          }`}
        >
          {items.map((item) => (
            <label
              key={item}
              className="flex items-center px-4 py-2 cursor-pointer dark:hover:bg-blue-100 hover:bg-gray-400"
            >
              <Checkbox
                id={`filter-${item}`}
                checked={isItemSelected(item)}
                onCheckedChange={() => toggleItem(item)}
                className="h-4 w-4 text-blue-600"
              />
              <span className="ml-2 text-sm text-dark dark:text-light">
                {item}
              </span>
            </label>
          ))}
        </div>
      )}
    </div>
  );
};

export default DropdownFilter;
